<?php

$loader = require 'vendor/autoload.php';
$loader->add('AppName', __DIR__.'/../src/');

namespace OCA\AmxGallery\Service;

use OCA\AmxGallery\IDynamicAlbum;

/**
 * Service class to manage dynamics albums based on mediatypes.
 */
class MediatypeService implements IDynamicAlbum {


    private $mediatypes = [
"x3d"=>["name"=>"3D Crossword Plugin","detail"=>"IANA: 3D Crossword Plugin","media"=>"application","type"=>"vnd.hzn-3d-crossword","group"=>""],
"3gp"=>["name"=>"3GP","detail"=>"Wikipedia: 3GP","media"=>"video","type"=>"3gpp","group"=>""],
"3g2"=>["name"=>"3GP2","detail"=>"Wikipedia: 3G2","media"=>"video","type"=>"3gpp2","group"=>""],
"mseq"=>["name"=>"3GPP MSEQ File","detail"=>"IANA: 3GPP MSEQ File","media"=>"application","type"=>"vnd.mseq","group"=>""],
"pwn"=>["name"=>"3M Post It Notes","detail"=>"IANA: 3M Post It Notes","media"=>"application","type"=>"vnd.3m.post-it-notes","group"=>""],
"plb"=>["name"=>"3rd Generation Partnership Project - Pic Large","detail"=>"3GPP","media"=>"application","type"=>"vnd.3gpp.pic-bw-large","group"=>""],
"psb"=>["name"=>"3rd Generation Partnership Project - Pic Small","detail"=>"3GPP","media"=>"application","type"=>"vnd.3gpp.pic-bw-small","group"=>""],
"pvb"=>["name"=>"3rd Generation Partnership Project - Pic Var","detail"=>"3GPP","media"=>"application","type"=>"vnd.3gpp.pic-bw-var","group"=>""],
"tcap"=>["name"=>"3rd Generation Partnership Project - Transaction Capabilities Application Part","detail"=>"3GPP","media"=>"application","type"=>"vnd.3gpp2.tcap","group"=>""],
"7z"=>["name"=>"7-Zip","detail"=>"Wikipedia: 7-Zip","media"=>"application","type"=>"x-7z-compressed","group"=>"compress"],
"abw"=>["name"=>"AbiWord","detail"=>"Wikipedia: AbiWord","media"=>"application","type"=>"x-abiword","group"=>""],
"ace"=>["name"=>"Ace Archive","detail"=>"Wikipedia: ACE","media"=>"application","type"=>"x-ace-compressed","group"=>""],
"acc"=>["name"=>"Active Content Compression","detail"=>"IANA: Active Content Compression","media"=>"application","type"=>"vnd.americandynamics.acc","group"=>""],
"acu"=>["name"=>"ACU Cobol","detail"=>"IANA: ACU Cobol","media"=>"application","type"=>"vnd.acucobol","group"=>""],
"atc"=>["name"=>"ACU Cobol","detail"=>"IANA: ACU Cobol","media"=>"application","type"=>"vnd.acucorp","group"=>""],
"adp"=>["name"=>"Adaptive differential pulse-code modulation","detail"=>"Wikipedia: ADPCM","media"=>"audio","type"=>"adpcm","group"=>""],
"aab"=>["name"=>"Adobe (Macropedia) Authorware - Binary File","detail"=>"Wikipedia: Authorware","media"=>"application","type"=>"x-authorware-bin","group"=>"adobe"],
"aam"=>["name"=>"Adobe (Macropedia) Authorware - Map","detail"=>"Wikipedia: Authorware","media"=>"application","type"=>"x-authorware-map","group"=>"adobe"],
"aas"=>["name"=>"Adobe (Macropedia) Authorware - Segment File","detail"=>"Wikipedia: Authorware","media"=>"application","type"=>"x-authorware-seg","group"=>"adobe"],
"air"=>["name"=>"Adobe AIR Application","detail"=>"Building AIR Applications","media"=>"application","type"=>"vnd.adobe.air-application-installer-package+zip","group"=>"adobe"],
"swf"=>["name"=>"Adobe Flash","detail"=>"Wikipedia: Adobe Flash","media"=>"application","type"=>"x-shockwave-flash","group"=>"adobe"],
"fxp"=>["name"=>"Adobe Flex Project","detail"=>"IANA: Adobe Flex Project","media"=>"application","type"=>"vnd.adobe.fxp","group"=>"adobe"],
"pdf"=>["name"=>"Adobe Portable Document Format","detail"=>"Adobe PDF","media"=>"application","type"=>"pdf","group"=>"adobe"],
"ppd"=>["name"=>"Adobe PostScript Printer Description File Format","detail"=>"IANA: Cups","media"=>"application","type"=>"vnd.cups-ppd","group"=>"adobe"],
"dir"=>["name"=>"Adobe Shockwave Player","detail"=>"Wikipedia: Adobe Shockwave Player","media"=>"application","type"=>"x-director","group"=>"adobe"],
"xdp"=>["name"=>"Adobe XML Data Package","detail"=>"Wikipedia: XML Data Package","media"=>"application","type"=>"vnd.adobe.xdp+xml","group"=>"adobe"],
"xfdf"=>["name"=>"Adobe XML Forms Data Format","detail"=>"Wikipedia: XML Portable Document Format","media"=>"application","type"=>"vnd.adobe.xfdf","group"=>"adobe"],
"aac"=>["name"=>"Advanced Audio Coding (AAC)","detail"=>"Wikipedia: AAC","media"=>"audio","type"=>"x-aac","group"=>""],
"ahead"=>["name"=>"Ahead AIR Application","detail"=>"IANA: Ahead AIR Application","media"=>"application","type"=>"vnd.ahead.space","group"=>""],
"azf"=>["name"=>"AirZip FileSECURE","detail"=>"IANA: AirZip","media"=>"application","type"=>"vnd.airzip.filesecure.azf","group"=>"compress"],
"azs"=>["name"=>"AirZip FileSECURE","detail"=>"IANA: AirZip","media"=>"application","type"=>"vnd.airzip.filesecure.azs","group"=>"compress"],
"azw"=>["name"=>"Amazon Kindle eBook format","detail"=>"Kindle Direct Publishing","media"=>"application","type"=>"vnd.amazon.ebook","group"=>""],
"ami"=>["name"=>"AmigaDE","detail"=>"IANA: Amiga","media"=>"application","type"=>"vnd.amiga.ami","group"=>""],
"N/A"=>["name"=>"Andrew Toolkit","detail"=>"IANA - Andrew Inset","media"=>"application","type"=>"andrew-inset","group"=>""],
"apk"=>["name"=>"Android Package Archive","detail"=>"Wikipedia: APK File Format","media"=>"application","type"=>"vnd.android.package-archive","group"=>""],
"cii"=>["name"=>"ANSER-WEB Terminal Client - Certificate Issue","detail"=>"IANA: ANSWER-WEB","media"=>"application","type"=>"vnd.anser-web-certificate-issue-initiation","group"=>""],
"fti"=>["name"=>"ANSER-WEB Terminal Client - Web Funds Transfer","detail"=>"IANA: ANSWER-WEB","media"=>"application","type"=>"vnd.anser-web-funds-transfer-initiation","group"=>""],
"atx"=>["name"=>"Antix Game Player","detail"=>"IANA: Antix Game Component","media"=>"application","type"=>"vnd.antix.game-component","group"=>""],
"dmg"=>["name"=>"Apple Disk Image","detail"=>"Apple Disk Image","media"=>"application","type"=>"x-apple-diskimage","group"=>"apple"],
"mpkg"=>["name"=>"Apple Installer Package","detail"=>"IANA: Apple Installer","media"=>"application","type"=>"vnd.apple.installer+xml","group"=>"apple"],
"aw"=>["name"=>"Applixware","detail"=>"Vistasource","media"=>"application","type"=>"applixware","group"=>""],
"les"=>["name"=>"Archipelago Lesson Player","detail"=>"IANA: Archipelago Lesson Player","media"=>"application","type"=>"vnd.hhe.lesson-player","group"=>""],
"swi"=>["name"=>"Arista Networks Software Image","detail"=>"IANA: Arista Networks Software Image","media"=>"application","type"=>"vnd.aristanetworks.swi","group"=>"graphic"],
"s"=>["name"=>"Assembler Source File","detail"=>"Wikipedia: Assembly","media"=>"text","type"=>"x-asm","group"=>""],
"atomcat"=>["name"=>"Atom Publishing Protocol","detail"=>"RFC 5023","media"=>"application","type"=>"atomcat+xml","group"=>""],
"atomsvc"=>["name"=>"Atom Publishing Protocol Service Document","detail"=>"RFC 5023","media"=>"application","type"=>"atomsvc+xml","group"=>""],
"atom"=>["name"=>"Atom Syndication Format","detail"=>"RFC 4287","media"=>"application","type"=>"atom+xml","group"=>""],
"ac"=>["name"=>"Attribute Certificate","detail"=>"RFC 5877","media"=>"application","type"=>"pkix-attr-cert","group"=>""],
"aif"=>["name"=>"Audio Interchange File Format","detail"=>"Wikipedia: Audio Interchange File Format","media"=>"audio","type"=>"x-aiff","group"=>"audio"],
"avi"=>["name"=>"Audio Video Interleave (AVI)","detail"=>"Wikipedia: AVI","media"=>"video","type"=>"x-msvideo","group"=>""],
"aep"=>["name"=>"Audiograph","detail"=>"IANA: Audiograph","media"=>"application","type"=>"vnd.audiograph","group"=>"audio"],
"dxf"=>["name"=>"AutoCAD DXF","detail"=>"Wikipedia: AutoCAD DXF","media"=>"image","type"=>"vnd.dxf","group"=>"graphic"],
"dwf"=>["name"=>"Autodesk Design Web Format (DWF)","detail"=>"Wikipedia: Design Web Format","media"=>"model","type"=>"vnd.dwf","group"=>"graphic"],
"par"=>["name"=>"BAS Partitur Format","detail"=>"Phonetik BAS","media"=>"text","type"=>"plain-bas","group"=>""],
"bcpio"=>["name"=>"Binary CPIO Archive","detail"=>"Wikipedia: cpio","media"=>"application","type"=>"x-bcpio","group"=>"raw"],
"bin"=>["name"=>"Binary Data","detail"=>"","media"=>"application","type"=>"octet-stream","group"=>"linux"],
"bmp"=>["name"=>"Bitmap Image File","detail"=>"Wikipedia: BMP File Format","media"=>"image","type"=>"bmp","group"=>"raw"],
"torrent"=>["name"=>"BitTorrent","detail"=>"Wikipedia: BitTorrent","media"=>"application","type"=>"x-bittorrent","group"=>"compress"],
"cod"=>["name"=>"Blackberry COD File","detail"=>"","media"=>"application","type"=>"vnd.rim.cod","group"=>""],
"mpm"=>["name"=>"Blueice Research Multipass","detail"=>"IANA: Multipass","media"=>"application","type"=>"vnd.blueice.multipass","group"=>""],
"bmi"=>["name"=>"BMI Drawing Data Interchange","detail"=>"IANA: BMI","media"=>"application","type"=>"vnd.bmi","group"=>""],
"sh"=>["name"=>"Bourne Shell Script","detail"=>"Wikipedia: Bourne Shell","media"=>"application","type"=>"x-sh","group"=>"linux"],
"btif"=>["name"=>"BTIF","detail"=>"IANA: BTIF","media"=>"image","type"=>"prs.btif","group"=>""],
"rep"=>["name"=>"BusinessObjects","detail"=>"IANA: BusinessObjects","media"=>"application","type"=>"vnd.businessobjects","group"=>""],
"bz"=>["name"=>"Bzip Archive","detail"=>"Wikipedia: Bzip","media"=>"application","type"=>"x-bzip","group"=>"compress"],
"bz2"=>["name"=>"Bzip2 Archive","detail"=>"Wikipedia: Bzip","media"=>"application","type"=>"x-bzip2","group"=>"compress"],
"csh"=>["name"=>"C Shell Script","detail"=>"Wikipedia: C Shell","media"=>"application","type"=>"x-csh","group"=>"linux"],
"c"=>["name"=>"C Source File","detail"=>"Wikipedia: C Programming Language","media"=>"text","type"=>"x-c","group"=>"program"],
"cdxml"=>["name"=>"CambridgeSoft Chem Draw","detail"=>"IANA: Chem Draw","media"=>"application","type"=>"vnd.chemdraw+xml","group"=>"xml"],
"css"=>["name"=>"Cascading Style Sheets (CSS)","detail"=>"Wikipedia: CSS","media"=>"text","type"=>"css","group"=>"web"],
"cdx"=>["name"=>"ChemDraw eXchange file","detail"=>"ChemDraw eXchange file","media"=>"chemical","type"=>"x-cdx","group"=>""],
"cml"=>["name"=>"Chemical Markup Language","detail"=>"Wikipedia: Chemical Markup Language","media"=>"chemical","type"=>"x-cml","group"=>""],
"csml"=>["name"=>"Chemical Style Markup Language","detail"=>"Wikipedia: Chemical Style Markup Language","media"=>"chemical","type"=>"x-csml","group"=>""],
"cdbcmsg"=>["name"=>"CIM Database","detail"=>"IANA: CIM Database","media"=>"application","type"=>"vnd.contact.cmsg","group"=>""],
"cla"=>["name"=>"Claymore Data Files","detail"=>"IANA: Claymore","media"=>"application","type"=>"vnd.claymore","group"=>""],
"c4g"=>["name"=>"Clonk Game","detail"=>"IANA: Clonk","media"=>"application","type"=>"vnd.clonk.c4group","group"=>""],
"sub"=>["name"=>"Close Captioning - Subtitle","detail"=>"Wikipedia: Closed Captioning","media"=>"image","type"=>"vnd.dvb.subtitle","group"=>""],
"cdmia"=>["name"=>"Cloud Data Management Interface (CDMI) - Capability","detail"=>"RFC 6208","media"=>"application","type"=>"cdmi-capability","group"=>""],
"cdmic"=>["name"=>"Cloud Data Management Interface (CDMI) - Contaimer","detail"=>"RFC 6209","media"=>"application","type"=>"cdmi-container","group"=>""],
"cdmid"=>["name"=>"Cloud Data Management Interface (CDMI) - Domain","detail"=>"RFC 6210","media"=>"application","type"=>"cdmi-domain","group"=>""],
"cdmio"=>["name"=>"Cloud Data Management Interface (CDMI) - Object","detail"=>"RFC 6211","media"=>"application","type"=>"cdmi-object","group"=>""],
"cdmiq"=>["name"=>"Cloud Data Management Interface (CDMI) - Queue","detail"=>"RFC 6212","media"=>"application","type"=>"cdmi-queue","group"=>""],
"c11amc"=>["name"=>"ClueTrust CartoMobile - Config","detail"=>"IANA: CartoMobile","media"=>"application","type"=>"vnd.cluetrust.cartomobile-config","group"=>""],
"c11amz"=>["name"=>"ClueTrust CartoMobile - Config Package","detail"=>"IANA: CartoMobile","media"=>"application","type"=>"vnd.cluetrust.cartomobile-config-pkg","group"=>""],
"ras"=>["name"=>"CMU Image","detail"=>"","media"=>"image","type"=>"x-cmu-raster","group"=>""],
"dae"=>["name"=>"COLLADA","detail"=>"IANA: COLLADA","media"=>"model","type"=>"vnd.collada+xml","group"=>"xml"],
"csv"=>["name"=>"Comma-Seperated Values","detail"=>"Wikipedia: CSV","media"=>"text","type"=>"csv","group"=>"document"],
"cpt"=>["name"=>"Compact Pro","detail"=>"Compact Pro","media"=>"application","type"=>"mac-compactpro","group"=>""],
"wmlc"=>["name"=>"Compiled Wireless Markup Language (WMLC)","detail"=>"IANA: WMLC","media"=>"application","type"=>"vnd.wap.wmlc","group"=>""],
"cgm"=>["name"=>"Computer Graphics Metafile","detail"=>"Wikipedia: Computer Graphics Metafile","media"=>"image","type"=>"cgm","group"=>"graphic"],
"ice"=>["name"=>"CoolTalk","detail"=>"Wikipedia: CoolTalk","media"=>"x-conference","type"=>"x-cooltalk","group"=>""],
"cmx"=>["name"=>"Corel Metafile Exchange (CMX)","detail"=>"Wikipedia: CorelDRAW","media"=>"image","type"=>"x-cmx","group"=>""],
"xar"=>["name"=>"CorelXARA","detail"=>"IANA: CorelXARA","media"=>"application","type"=>"vnd.xara","group"=>""],
"cmc"=>["name"=>"CosmoCaller","detail"=>"IANA: CosmoCaller","media"=>"application","type"=>"vnd.cosmocaller","group"=>""],
"cpio"=>["name"=>"CPIO Archive","detail"=>"Wikipedia: cpio","media"=>"application","type"=>"x-cpio","group"=>"web"],
"clkx"=>["name"=>"CrickSoftware - Clicker","detail"=>"IANA: Clicker","media"=>"application","type"=>"vnd.crick.clicker","group"=>""],
"clkk"=>["name"=>"CrickSoftware - Clicker - Keyboard","detail"=>"IANA: Clicker","media"=>"application","type"=>"vnd.crick.clicker.keyboard","group"=>"cricksoftware"],
"clkp"=>["name"=>"CrickSoftware - Clicker - Palette","detail"=>"IANA: Clicker","media"=>"application","type"=>"vnd.crick.clicker.palette","group"=>"cricksoftware"],
"clkt"=>["name"=>"CrickSoftware - Clicker - Template","detail"=>"IANA: Clicker","media"=>"application","type"=>"vnd.crick.clicker.template","group"=>"cricksoftware"],
"clkw"=>["name"=>"CrickSoftware - Clicker - Wordbank","detail"=>"IANA: Clicker","media"=>"application","type"=>"vnd.crick.clicker.wordbank","group"=>"cricksoftware"],
"wbs"=>["name"=>"Critical Tools - PERT Chart EXPERT","detail"=>"IANA: Critical Tools","media"=>"application","type"=>"vnd.criticaltools.wbs+xml","group"=>""],
"cryptonote"=>["name"=>"CryptoNote","detail"=>"IANA: CryptoNote","media"=>"application","type"=>"vnd.rig.cryptonote","group"=>""],
"cif"=>["name"=>"Crystallographic Interchange Format","detail"=>"Crystallographic Interchange Format","media"=>"chemical","type"=>"x-cif","group"=>"graphic"],
"cmdf"=>["name"=>"CrystalMaker Data Format","detail"=>"CrystalMaker Data Format","media"=>"chemical","type"=>"x-cmdf","group"=>""],
"cu"=>["name"=>"CU-SeeMe","detail"=>"White Pine","media"=>"application","type"=>"cu-seeme","group"=>""],
"cww"=>["name"=>"CU-Writer","detail"=>"","media"=>"application","type"=>"prs.cww","group"=>""],
"curl"=>["name"=>"Curl - Applet","detail"=>"Curl Applet","media"=>"text","type"=>"vnd.curl","group"=>""],
"dcurl"=>["name"=>"Curl - Detached Applet","detail"=>"Curl Detached Applet","media"=>"text","type"=>"vnd.curl.dcurl","group"=>""],
"mcurl"=>["name"=>"Curl - Manifest File","detail"=>"Curl Manifest File","media"=>"text","type"=>"vnd.curl.mcurl","group"=>""],
"scurl"=>["name"=>"Curl - Source Code","detail"=>"Curl Source Code","media"=>"text","type"=>"vnd.curl.scurl","group"=>""],
"car"=>["name"=>"CURL Applet","detail"=>"IANA: CURL Applet","media"=>"application","type"=>"vnd.curl.car","group"=>""],
"pcurl"=>["name"=>"CURL Applet","detail"=>"IANA: CURL Applet","media"=>"application","type"=>"vnd.curl.pcurl","group"=>""],
"cmp"=>["name"=>"CustomMenu","detail"=>"IANA: CustomMenu","media"=>"application","type"=>"vnd.yellowriver-custom-menu","group"=>""],
"dssc"=>["name"=>"Data Structure for the Security Suitability of Cryptographic Algorithms","detail"=>"RFC 5698","media"=>"application","type"=>"dssc+der","group"=>""],
"xdssc"=>["name"=>"Data Structure for the Security Suitability of Cryptographic Algorithms","detail"=>"RFC 5698","media"=>"application","type"=>"dssc+xml","group"=>""],
"deb"=>["name"=>"Debian Package","detail"=>"Wikipedia: Debian Package","media"=>"application","type"=>"x-debian-package","group"=>"linux"],
"uva"=>["name"=>"DECE Audio","detail"=>"IANA: Dece Audio","media"=>"audio","type"=>"vnd.dece.audio","group"=>""],
"uvi"=>["name"=>"DECE Graphic","detail"=>"IANA: DECE Graphic","media"=>"image","type"=>"vnd.dece.graphic","group"=>"graphic"],
"uvh"=>["name"=>"DECE High Definition Video","detail"=>"IANA: DECE HD Video","media"=>"video","type"=>"vnd.dece.hd","group"=>""],
"uvm"=>["name"=>"DECE Mobile Video","detail"=>"IANA: DECE Mobile Video","media"=>"video","type"=>"vnd.dece.mobile","group"=>""],
"uvu"=>["name"=>"DECE MP4","detail"=>"IANA: DECE MP4","media"=>"video","type"=>"vnd.uvvu.mp4","group"=>""],
"uvp"=>["name"=>"DECE PD Video","detail"=>"IANA: DECE PD Video","media"=>"video","type"=>"vnd.dece.pd","group"=>""],
"uvs"=>["name"=>"DECE SD Video","detail"=>"IANA: DECE SD Video","media"=>"video","type"=>"vnd.dece.sd","group"=>""],
"uvv"=>["name"=>"DECE Video","detail"=>"IANA: DECE Video","media"=>"video","type"=>"vnd.dece.video","group"=>""],
"dvi"=>["name"=>"Device Independent File Format (DVI)","detail"=>"Wikipedia: DVI","media"=>"application","type"=>"x-dvi","group"=>""],
"seed"=>["name"=>"Digital Siesmograph Networks - SEED Datafiles","detail"=>"IANA: SEED","media"=>"application","type"=>"vnd.fdsn.seed","group"=>""],
"dtb"=>["name"=>"Digital Talking Book","detail"=>"Wikipedia: EPUB","media"=>"application","type"=>"x-dtbook+xml","group"=>""],
"res"=>["name"=>"Digital Talking Book - Resource File","detail"=>"Digital Talking Book","media"=>"application","type"=>"x-dtbresource+xml","group"=>""],
"ait"=>["name"=>"Digital Video Broadcasting","detail"=>"IANA: Digital Video Broadcasting","media"=>"application","type"=>"vnd.dvb.ait","group"=>""],
"svc"=>["name"=>"Digital Video Broadcasting","detail"=>"IANA: Digital Video Broadcasting","media"=>"application","type"=>"vnd.dvb.service","group"=>""],
"eol"=>["name"=>"Digital Winds Music","detail"=>"IANA: Digital Winds","media"=>"audio","type"=>"vnd.digital-winds","group"=>""],
"djvu"=>["name"=>"DjVu","detail"=>"Wikipedia: DjVu","media"=>"image","type"=>"vnd.djvu","group"=>""],
"dtd"=>["name"=>"Document Type Definition","detail"=>"W3C DTD","media"=>"application","type"=>"xml-dtd","group"=>"xml"],
"mlp"=>["name"=>"Dolby Meridian Lossless Packing","detail"=>"IANA: Dolby Meridian Lossless Packing","media"=>"application","type"=>"vnd.dolby.mlp","group"=>""],
"wad"=>["name"=>"Doom Video Game","detail"=>"Wikipedia: Doom WAD","media"=>"application","type"=>"x-doom","group"=>""],
"dpg"=>["name"=>"DPGraph","detail"=>"IANA: DPGraph","media"=>"application","type"=>"vnd.dpgraph","group"=>""],
"dra"=>["name"=>"DRA Audio","detail"=>"IANA: DRA","media"=>"audio","type"=>"vnd.dra","group"=>""],
"dfac"=>["name"=>"DreamFactory","detail"=>"IANA: DreamFactory","media"=>"application","type"=>"vnd.dreamfactory","group"=>""],
"dts"=>["name"=>"DTS Audio","detail"=>"IANA: DTS","media"=>"audio","type"=>"vnd.dts","group"=>""],
"dtshd"=>["name"=>"DTS High Definition Audio","detail"=>"IANA: DTS HD","media"=>"audio","type"=>"vnd.dts.hd","group"=>""],
"dwg"=>["name"=>"DWG Drawing","detail"=>"Wikipedia: DWG","media"=>"image","type"=>"vnd.dwg","group"=>"graphic"],
"geo"=>["name"=>"DynaGeo","detail"=>"IANA: DynaGeo","media"=>"application","type"=>"vnd.dynageo","group"=>""],
"es"=>["name"=>"ECMAScript","detail"=>"ECMA-357","media"=>"application","type"=>"ecmascript","group"=>""],
"mag"=>["name"=>"EcoWin Chart","detail"=>"IANA: EcoWin Chart","media"=>"application","type"=>"vnd.ecowin.chart","group"=>""],
"mmr"=>["name"=>"EDMICS 2000","detail"=>"IANA: EDMICS 2000","media"=>"image","type"=>"vnd.fujixerox.edmics-mmr","group"=>""],
"rlc"=>["name"=>"EDMICS 2000","detail"=>"IANA: EDMICS 2000","media"=>"image","type"=>"vnd.fujixerox.edmics-rlc","group"=>""],
"exi"=>["name"=>"Efficient XML Interchange","detail"=>"Efficient XML Interchange (EXI) Best Practices","media"=>"application","type"=>"exi","group"=>""],
"mgz"=>["name"=>"EFI Proteus","detail"=>"IANA: EFI Proteus","media"=>"application","type"=>"vnd.proteus.magazine","group"=>""],
"epub"=>["name"=>"Electronic Publication","detail"=>"Wikipedia: EPUB","media"=>"application","type"=>"epub+zip","group"=>"book"],
"eml"=>["name"=>"Email Message","detail"=>"RFC 2822","media"=>"message","type"=>"rfc822","group"=>""],
"nml"=>["name"=>"Enliven Viewer","detail"=>"IANA: Enliven Viewer","media"=>"application","type"=>"vnd.enliven","group"=>""],
"xpr"=>["name"=>"Express by Infoseek","detail"=>"IANA: Express by Infoseek","media"=>"application","type"=>"vnd.is-xpr","group"=>""],
"xif"=>["name"=>"eXtended Image File Format (XIFF)","detail"=>"IANA: XIFF","media"=>"image","type"=>"vnd.xiff","group"=>""],
"xfdl"=>["name"=>"Extensible Forms Description Language","detail"=>"IANA: Extensible Forms Description Language","media"=>"application","type"=>"vnd.xfdl","group"=>""],
"emma"=>["name"=>"Extensible MultiModal Annotation","detail"=>"EMMA: Extensible MultiModal Annotation markup language","media"=>"application","type"=>"emma+xml","group"=>""],
"ez2"=>["name"=>"EZPix Secure Photo Album","detail"=>"IANA: EZPix Secure Photo Album","media"=>"application","type"=>"vnd.ezpix-album","group"=>""],
"ez3"=>["name"=>"EZPix Secure Photo Album","detail"=>"IANA: EZPix Secure Photo Album","media"=>"application","type"=>"vnd.ezpix-package","group"=>""],
"fst"=>["name"=>"FAST Search & Transfer ASA","detail"=>"IANA: FAST Search & Transfer ASA","media"=>"image","type"=>"vnd.fst","group"=>""],
"fvt"=>["name"=>"FAST Search & Transfer ASA","detail"=>"IANA: FVT","media"=>"video","type"=>"vnd.fvt","group"=>""],
"fbs"=>["name"=>"FastBid Sheet","detail"=>"IANA: FastBid Sheet","media"=>"image","type"=>"vnd.fastbidsheet","group"=>""],
"fe_launch"=>["name"=>"FCS Express Layout Link","detail"=>"IANA: FCS Express Layout Link","media"=>"application","type"=>"vnd.denovo.fcselayout-link","group"=>""],
"f4v"=>["name"=>"Flash Video","detail"=>"Wikipedia: Flash Video","media"=>"video","type"=>"x-f4v","group"=>"adobe"],
"flv"=>["name"=>"Flash Video","detail"=>"Wikipedia: Flash Video","media"=>"video","type"=>"x-flv","group"=>"adobe"],
"fpx"=>["name"=>"FlashPix","detail"=>"IANA: FPX","media"=>"image","type"=>"vnd.fpx","group"=>"adobe"],
"npx"=>["name"=>"FlashPix","detail"=>"IANA: FPX","media"=>"image","type"=>"vnd.net-fpx","group"=>"adobe"],
"flx"=>["name"=>"FLEXSTOR","detail"=>"IANA: FLEXSTOR","media"=>"text","type"=>"vnd.fmi.flexstor","group"=>""],
"fli"=>["name"=>"FLI/FLC Animation Format","detail"=>"FLI/FLC Animation Format","media"=>"video","type"=>"x-fli","group"=>""],
"ftc"=>["name"=>"FluxTime Clip","detail"=>"IANA: FluxTime Clip","media"=>"application","type"=>"vnd.fluxtime.clip","group"=>""],
"fdf"=>["name"=>"Forms Data Format","detail"=>"IANA: Forms Data Format","media"=>"application","type"=>"vnd.fdf","group"=>""],
"f"=>["name"=>"Fortran Source File","detail"=>"Wikipedia: Fortran","media"=>"text","type"=>"x-fortran","group"=>"program"],
"mif"=>["name"=>"FrameMaker Interchange Format","detail"=>"IANA: FrameMaker Interchange Format","media"=>"application","type"=>"vnd.mif","group"=>""],
"fm"=>["name"=>"FrameMaker Normal Format","detail"=>"IANA: FrameMaker","media"=>"application","type"=>"vnd.framemaker","group"=>""],
"fh"=>["name"=>"FreeHand MX","detail"=>"Wikipedia: Macromedia Freehand","media"=>"image","type"=>"x-freehand","group"=>""],
"fsc"=>["name"=>"Friendly Software Corporation","detail"=>"IANA: Friendly Software Corporation","media"=>"application","type"=>"vnd.fsc.weblaunch","group"=>""],
"fnc"=>["name"=>"Frogans Player","detail"=>"IANA: Frogans Player","media"=>"application","type"=>"vnd.frogans.fnc","group"=>""],
"ltf"=>["name"=>"Frogans Player","detail"=>"IANA: Frogans Player","media"=>"application","type"=>"vnd.frogans.ltf","group"=>""],
"ddd"=>["name"=>"Fujitsu - Xerox 2D CAD Data","detail"=>"IANA: Fujitsu DDD","media"=>"application","type"=>"vnd.fujixerox.ddd","group"=>""],
"xdw"=>["name"=>"Fujitsu - Xerox DocuWorks","detail"=>"IANA: Docuworks","media"=>"application","type"=>"vnd.fujixerox.docuworks","group"=>""],
"xbd"=>["name"=>"Fujitsu - Xerox DocuWorks Binder","detail"=>"IANA: Docuworks Binder","media"=>"application","type"=>"vnd.fujixerox.docuworks.binder","group"=>""],
"oas"=>["name"=>"Fujitsu Oasys","detail"=>"IANA: Fujitsu Oasys","media"=>"application","type"=>"vnd.fujitsu.oasys","group"=>""],
"oa2"=>["name"=>"Fujitsu Oasys","detail"=>"IANA: Fujitsu Oasys","media"=>"application","type"=>"vnd.fujitsu.oasys2","group"=>""],
"oa3"=>["name"=>"Fujitsu Oasys","detail"=>"IANA: Fujitsu Oasys","media"=>"application","type"=>"vnd.fujitsu.oasys3","group"=>""],
"fg5"=>["name"=>"Fujitsu Oasys","detail"=>"IANA: Fujitsu Oasys","media"=>"application","type"=>"vnd.fujitsu.oasysgp","group"=>""],
"bh2"=>["name"=>"Fujitsu Oasys","detail"=>"IANA: Fujitsu Oasys","media"=>"application","type"=>"vnd.fujitsu.oasysprs","group"=>""],
"spl"=>["name"=>"FutureSplash Animator","detail"=>"Wikipedia: FutureSplash Animator","media"=>"application","type"=>"x-futuresplash","group"=>""],
"fzs"=>["name"=>"FuzzySheet","detail"=>"IANA: FuzySheet","media"=>"application","type"=>"vnd.fuzzysheet","group"=>""],
"g3"=>["name"=>"G3 Fax Image","detail"=>"Wikipedia: G3 Fax Image","media"=>"image","type"=>"g3fax","group"=>""],
"gmx"=>["name"=>"GameMaker ActiveX","detail"=>"IANA: GameMaker ActiveX","media"=>"application","type"=>"vnd.gmx","group"=>""],
"gtw"=>["name"=>"Gen-Trix Studio","detail"=>"IANA: GTW","media"=>"model","type"=>"vnd.gtw","group"=>""],
"txd"=>["name"=>"Genomatix Tuxedo Framework","detail"=>"IANA: Genomatix Tuxedo Framework","media"=>"application","type"=>"vnd.genomatix.tuxedo","group"=>""],
"ggb"=>["name"=>"GeoGebra","detail"=>"IANA: GeoGebra","media"=>"application","type"=>"vnd.geogebra.file","group"=>""],
"ggt"=>["name"=>"GeoGebra","detail"=>"IANA: GeoGebra","media"=>"application","type"=>"vnd.geogebra.tool","group"=>""],
"gdl"=>["name"=>"Geometric Description Language (GDL)","detail"=>"IANA: GDL","media"=>"model","type"=>"vnd.gdl","group"=>""],
"gex"=>["name"=>"GeoMetry Explorer","detail"=>"IANA: GeoMetry Explorer","media"=>"application","type"=>"vnd.geometry-explorer","group"=>""],
"gxt"=>["name"=>"GEONExT and JSXGraph","detail"=>"IANA: GEONExT and JSXGraph","media"=>"application","type"=>"vnd.geonext","group"=>""],
"g2w"=>["name"=>"GeoplanW","detail"=>"IANA: GeoplanW","media"=>"application","type"=>"vnd.geoplan","group"=>""],
"g3w"=>["name"=>"GeospacW","detail"=>"IANA: GeospacW","media"=>"application","type"=>"vnd.geospace","group"=>""],
"gsf"=>["name"=>"Ghostscript Font","detail"=>"Wikipedia: Ghostscript","media"=>"application","type"=>"x-font-ghostscript","group"=>"font"],
"bdf"=>["name"=>"Glyph Bitmap Distribution Format","detail"=>"Wikipedia: Glyph Bitmap Distribution Format","media"=>"application","type"=>"x-font-bdf","group"=>"font"],
"gtar"=>["name"=>"GNU Tar Files","detail"=>"GNU Tar","media"=>"application","type"=>"x-gtar","group"=>"compress"],
"texinfo"=>["name"=>"GNU Texinfo Document","detail"=>"Wikipedia: Texinfo","media"=>"application","type"=>"x-texinfo","group"=>"web"],
"gnumeric"=>["name"=>"Gnumeric","detail"=>"Wikipedia: Gnumeric","media"=>"application","type"=>"x-gnumeric","group"=>"web"],
"kml"=>["name"=>"Google Earth - KML","detail"=>"IANA: Google Earth","media"=>"application","type"=>"vnd.google-earth.kml+xml","group"=>"google"],
"kmz"=>["name"=>"Google Earth - Zipped KML","detail"=>"IANA: Google Earth","media"=>"application","type"=>"vnd.google-earth.kmz","group"=>"google"],
"gqf"=>["name"=>"GrafEq","detail"=>"IANA: GrafEq","media"=>"application","type"=>"vnd.grafeq","group"=>""],
"gif"=>["name"=>"Graphics Interchange Format","detail"=>"Wikipedia: Graphics Interchange Format","media"=>"image","type"=>"gif","group"=>"graphic"],
"gv"=>["name"=>"Graphviz","detail"=>"IANA: Graphviz","media"=>"text","type"=>"vnd.graphviz","group"=>""],
"gac"=>["name"=>"Groove - Account","detail"=>"IANA: Groove","media"=>"application","type"=>"vnd.groove-account","group"=>""],
"ghf"=>["name"=>"Groove - Help","detail"=>"IANA: Groove","media"=>"application","type"=>"vnd.groove-help","group"=>""],
"gim"=>["name"=>"Groove - Identity Message","detail"=>"IANA: Groove","media"=>"application","type"=>"vnd.groove-identity-message","group"=>""],
"grv"=>["name"=>"Groove - Injector","detail"=>"IANA: Groove","media"=>"application","type"=>"vnd.groove-injector","group"=>""],
"gtm"=>["name"=>"Groove - Tool Message","detail"=>"IANA: Groove","media"=>"application","type"=>"vnd.groove-tool-message","group"=>""],
"tpl"=>["name"=>"Groove - Tool Template","detail"=>"IANA: Groove","media"=>"application","type"=>"vnd.groove-tool-template","group"=>""],
"vcg"=>["name"=>"Groove - Vcard","detail"=>"IANA: Groove","media"=>"application","type"=>"vnd.groove-vcard","group"=>""],
"h261"=>["name"=>"H.261","detail"=>"Wikipedia: H.261","media"=>"video","type"=>"h261","group"=>""],
"h263"=>["name"=>"H.263","detail"=>"Wikipedia: H.263","media"=>"video","type"=>"h263","group"=>""],
"h264"=>["name"=>"H.264","detail"=>"Wikipedia: H.264","media"=>"video","type"=>"h264","group"=>""],
"hpid"=>["name"=>"Hewlett Packard Instant Delivery","detail"=>"IANA: Hewlett Packard Instant Delivery","media"=>"application","type"=>"vnd.hp-hpid","group"=>""],
"hps"=>["name"=>"Hewlett-Packard's WebPrintSmart","detail"=>"IANA: Hewlett-Packard's WebPrintSmart","media"=>"application","type"=>"vnd.hp-hps","group"=>""],
"hdf"=>["name"=>"Hierarchical Data Format","detail"=>"Wikipedia: Hierarchical Data Format","media"=>"application","type"=>"x-hdf","group"=>""],
"rip"=>["name"=>"Hit'n'Mix","detail"=>"IANA: Hit'n'Mix","media"=>"audio","type"=>"vnd.rip","group"=>""],
"hbci"=>["name"=>"Homebanking Computer Interface (HBCI)","detail"=>"IANA: HBCI","media"=>"application","type"=>"vnd.hbci","group"=>""],
"jlt"=>["name"=>"HP Indigo Digital Press - Job Layout Languate","detail"=>"IANA: HP Job Layout Language","media"=>"application","type"=>"vnd.hp-jlyt","group"=>""],
"pcl"=>["name"=>"HP Printer Command Language","detail"=>"IANA: HP Printer Command Language","media"=>"application","type"=>"vnd.hp-pcl","group"=>""],
"hpgl"=>["name"=>"HP-GL/2 and HP RTL","detail"=>"IANA: HP-GL/2 and HP RTL","media"=>"application","type"=>"vnd.hp-hpgl","group"=>""],
"hvs"=>["name"=>"HV Script","detail"=>"IANA: HV Script","media"=>"application","type"=>"vnd.yamaha.hv-script","group"=>""],
"hvd"=>["name"=>"HV Voice Dictionary","detail"=>"IANA: HV Voice Dictionary","media"=>"application","type"=>"vnd.yamaha.hv-dic","group"=>""],
"hvp"=>["name"=>"HV Voice Parameter","detail"=>"IANA: HV Voice Parameter","media"=>"application","type"=>"vnd.yamaha.hv-voice","group"=>""],
"sfd-hdstx"=>["name"=>"Hydrostatix Master Suite","detail"=>"IANA: Hydrostatix Master Suite","media"=>"application","type"=>"vnd.hydrostatix.sof-data","group"=>""],
"stk"=>["name"=>"Hyperstudio","detail"=>"IANA - Hyperstudio","media"=>"application","type"=>"hyperstudio","group"=>""],
"hal"=>["name"=>"Hypertext Application Language","detail"=>"IANA: HAL","media"=>"application","type"=>"vnd.hal+xml","group"=>""],
"html"=>["name"=>"HyperText Markup Language (HTML)","detail"=>"Wikipedia: HTML","media"=>"text","type"=>"html","group"=>"web"],
"irm"=>["name"=>"IBM DB2 Rights Manager","detail"=>"IANA: IBM DB2 Rights Manager","media"=>"application","type"=>"vnd.ibm.rights-management","group"=>""],
"sc"=>["name"=>"IBM Electronic Media Management System - Secure Container","detail"=>"IANA: EMMS","media"=>"application","type"=>"vnd.ibm.secure-container","group"=>""],
"ics"=>["name"=>"iCalendar","detail"=>"Wikipedia: iCalendar","media"=>"text","type"=>"calendar","group"=>""],
"icc"=>["name"=>"ICC profile","detail"=>"IANA: ICC profile","media"=>"application","type"=>"vnd.iccprofile","group"=>""],
"ico"=>["name"=>"Icon Image","detail"=>"Wikipedia: ICO File Format","media"=>"image","type"=>"x-icon","group"=>""],
"igl"=>["name"=>"igLoader","detail"=>"IANA: igLoader","media"=>"application","type"=>"vnd.igloader","group"=>""],
"ief"=>["name"=>"Image Exchange Format","detail"=>"RFC 1314","media"=>"image","type"=>"ief","group"=>""],
"ivp"=>["name"=>"ImmerVision PURE Players","detail"=>"IANA: ImmerVision PURE Players","media"=>"application","type"=>"vnd.immervision-ivp","group"=>""],
"ivu"=>["name"=>"ImmerVision PURE Players","detail"=>"IANA: ImmerVision PURE Players","media"=>"application","type"=>"vnd.immervision-ivu","group"=>""],
"rif"=>["name"=>"IMS Networks","detail"=>"","media"=>"application","type"=>"reginfo+xml","group"=>""],
"3dml"=>["name"=>"In3D - 3DML","detail"=>"IANA: In3D","media"=>"text","type"=>"vnd.in3d.3dml","group"=>""],
"spot"=>["name"=>"In3D - 3DML","detail"=>"IANA: In3D","media"=>"text","type"=>"vnd.in3d.spot","group"=>""],
"igs"=>["name"=>"Initial Graphics Exchange Specification (IGES)","detail"=>"Wikipedia: IGES","media"=>"model","type"=>"iges","group"=>"graphic"],
"i2g"=>["name"=>"Interactive Geometry Software","detail"=>"IANA: Interactive Geometry Software","media"=>"application","type"=>"vnd.intergeo","group"=>"graphic"],
"cdy"=>["name"=>"Interactive Geometry Software Cinderella","detail"=>"IANA: Cinderella","media"=>"application","type"=>"vnd.cinderella","group"=>"graphic"],
"xpw"=>["name"=>"Intercon FormNet","detail"=>"IANA: Intercon FormNet","media"=>"application","type"=>"vnd.intercon.formnet","group"=>""],
"fcs"=>["name"=>"International Society for Advancement of Cytometry","detail"=>"IANA: International Society for Advancement of Cytometry","media"=>"application","type"=>"vnd.isac.fcs","group"=>""],
"ipfix"=>["name"=>"Internet Protocol Flow Information Export","detail"=>"RFC 3917","media"=>"application","type"=>"ipfix","group"=>"web"],
"cer"=>["name"=>"Internet Public Key Infrastructure - Certificate","detail"=>"RFC 2585","media"=>"application","type"=>"pkix-cert","group"=>"cryptographic"],
"pki"=>["name"=>"Internet Public Key Infrastructure - Certificate Management Protocole","detail"=>"RFC 2585","media"=>"application","type"=>"pkixcmp","group"=>"cryptographic"],
"crl"=>["name"=>"Internet Public Key Infrastructure - Certificate Revocation Lists","detail"=>"RFC 2585","media"=>"application","type"=>"pkix-crl","group"=>"cryptographic"],
"pkipath"=>["name"=>"Internet Public Key Infrastructure - Certification Path","detail"=>"RFC 2585","media"=>"application","type"=>"pkix-pkipath","group"=>"cryptographic"],
"igm"=>["name"=>"IOCOM Visimeet","detail"=>"IANA: IOCOM Visimeet","media"=>"application","type"=>"vnd.insors.igm","group"=>""],
"rcprofile"=>["name"=>"IP Unplugged Roaming Client","detail"=>"IANA: IP Unplugged Roaming Client","media"=>"application","type"=>"vnd.ipunplugged.rcprofile","group"=>""],
"irp"=>["name"=>"iRepository / Lucidoc Editor","detail"=>"IANA: iRepository / Lucidoc Editor","media"=>"application","type"=>"vnd.irepository.package+xml","group"=>""],
"jad"=>["name"=>"J2ME App Descriptor","detail"=>"IANA: J2ME App Descriptor","media"=>"text","type"=>"vnd.sun.j2me.app-descriptor","group"=>"progrm"],
"jar"=>["name"=>"Java Archive","detail"=>"Wikipedia: JAR file format","media"=>"application","type"=>"java-archive","group"=>"program"],
"class"=>["name"=>"Java Bytecode File","detail"=>"Wikipedia: Java Bytecode","media"=>"application","type"=>"java-vm","group"=>"program"],
"jnlp"=>["name"=>"Java Network Launching Protocol","detail"=>"Wikipedia: Java Web Start","media"=>"application","type"=>"x-java-jnlp-file","group"=>""],
"ser"=>["name"=>"Java Serialized Object","detail"=>"Java Serialization API","media"=>"application","type"=>"java-serialized-object","group"=>""],
"java"=>["name"=>"Java Source File","detail"=>"Wikipedia: Java","media"=>"text","type"=>"x-java-source,java","group"=>"program"],
"js"=>["name"=>"JavaScript","detail"=>"JavaScript","media"=>"application","type"=>"javascript","group"=>"web"],
"json"=>["name"=>"JavaScript Object Notation (JSON)","detail"=>"Wikipedia: JSON","media"=>"application","type"=>"json","group"=>"web"],
"joda"=>["name"=>"Joda Archive","detail"=>"IANA: Joda Archive","media"=>"application","type"=>"vnd.joost.joda-archive","group"=>""],
"jpm"=>["name"=>"JPEG 2000 Compound Image File Format","detail"=>"IANA: JPM","media"=>"video","type"=>"jpm","group"=>""],
"jpeg"=>["name"=>"JPEG Image","detail"=>"RFC 1314","media"=>"image","type"=>"jpeg","group"=>""],
"jpg"=>["name"=>"JPEG Image (Citrix client)","detail"=>"RFC 1314","media"=>"image","type"=>"x-citrix-jpeg","group"=>""],
"pjpeg"=>["name"=>"JPEG Image (Progressive)","detail"=>"JPEG image compression FAQ","media"=>"image","type"=>"pjpeg","group"=>""],
"jpgv"=>["name"=>"JPGVideo","detail"=>"RFC 3555","media"=>"video","type"=>"jpeg","group"=>""],
"ktz"=>["name"=>"Kahootz","detail"=>"IANA: Kahootz","media"=>"application","type"=>"vnd.kahootz","group"=>""],
"mmd"=>["name"=>"Karaoke on Chipnuts Chipsets","detail"=>"IANA: Chipnuts Karaoke","media"=>"application","type"=>"vnd.chipnuts.karaoke-mmd","group"=>""],
"karbon"=>["name"=>"KDE KOffice Office Suite - Karbon","detail"=>"IANA: KDE KOffice Office Suite","media"=>"application","type"=>"vnd.kde.karbon","group"=>""],
"chrt"=>["name"=>"KDE KOffice Office Suite - KChart","detail"=>"IANA: KDE KOffice Office Suite","media"=>"application","type"=>"vnd.kde.kchart","group"=>""],
"kfo"=>["name"=>"KDE KOffice Office Suite - Kformula","detail"=>"IANA: KDE KOffice Office Suite","media"=>"application","type"=>"vnd.kde.kformula","group"=>""],
"flw"=>["name"=>"KDE KOffice Office Suite - Kivio","detail"=>"IANA: KDE KOffice Office Suite","media"=>"application","type"=>"vnd.kde.kivio","group"=>""],
"kon"=>["name"=>"KDE KOffice Office Suite - Kontour","detail"=>"IANA: KDE KOffice Office Suite","media"=>"application","type"=>"vnd.kde.kontour","group"=>""],
"kpr"=>["name"=>"KDE KOffice Office Suite - Kpresenter","detail"=>"IANA: KDE KOffice Office Suite","media"=>"application","type"=>"vnd.kde.kpresenter","group"=>""],
"ksp"=>["name"=>"KDE KOffice Office Suite - Kspread","detail"=>"IANA: KDE KOffice Office Suite","media"=>"application","type"=>"vnd.kde.kspread","group"=>""],
"kwd"=>["name"=>"KDE KOffice Office Suite - Kword","detail"=>"IANA: KDE KOffice Office Suite","media"=>"application","type"=>"vnd.kde.kword","group"=>""],
"htke"=>["name"=>"Kenamea App","detail"=>"IANA: Kenamea App","media"=>"application","type"=>"vnd.kenameaapp","group"=>""],
"kia"=>["name"=>"Kidspiration","detail"=>"IANA: Kidspiration","media"=>"application","type"=>"vnd.kidspiration","group"=>""],
"kne"=>["name"=>"Kinar Applications","detail"=>"IANA: Kina Applications","media"=>"application","type"=>"vnd.kinar","group"=>""],
"sse"=>["name"=>"Kodak Storyshare","detail"=>"IANA: Kodak Storyshare","media"=>"application","type"=>"vnd.kodak-descriptor","group"=>""],
"lasxml"=>["name"=>"Laser App Enterprise","detail"=>"IANA: Laser App Enterprise","media"=>"application","type"=>"vnd.las.las+xml","group"=>"xml"],
"latex"=>["name"=>"LaTeX","detail"=>"Wikipedia: LaTeX","media"=>"application","type"=>"x-latex","group"=>""],
"lbd"=>["name"=>"Life Balance - Desktop Edition","detail"=>"IANA: Life Balance","media"=>"application","type"=>"vnd.llamagraphics.life-balance.desktop","group"=>""],
"lbe"=>["name"=>"Life Balance - Exchange Format","detail"=>"IANA: Life Balance","media"=>"application","type"=>"vnd.llamagraphics.life-balance.exchange+xml","group"=>""],
"jam"=>["name"=>"Lightspeed Audio Lab","detail"=>"IANA: Lightspeed Audio Lab","media"=>"application","type"=>"vnd.jam","group"=>""],
"0.123"=>["name"=>"Lotus 1-2-3","detail"=>"IANA: Lotus 1-2-3","media"=>"application","type"=>"vnd.lotus-1-2-3","group"=>"lotus"],
"apr"=>["name"=>"Lotus Approach","detail"=>"IANA: Lotus Approach","media"=>"application","type"=>"vnd.lotus-approach","group"=>"lotus"],
"pre"=>["name"=>"Lotus Freelance","detail"=>"IANA: Lotus Freelance","media"=>"application","type"=>"vnd.lotus-freelance","group"=>"lotus"],
"nsf"=>["name"=>"Lotus Notes","detail"=>"IANA: Lotus Notes","media"=>"application","type"=>"vnd.lotus-notes","group"=>"lotus"],
"org"=>["name"=>"Lotus Organizer","detail"=>"IANA: Lotus Organizer","media"=>"application","type"=>"vnd.lotus-organizer","group"=>"lotus"],
"scm"=>["name"=>"Lotus Screencam","detail"=>"IANA: Lotus Screencam","media"=>"application","type"=>"vnd.lotus-screencam","group"=>"lotus"],
"lwp"=>["name"=>"Lotus Wordpro","detail"=>"IANA: Lotus Wordpro","media"=>"application","type"=>"vnd.lotus-wordpro","group"=>"lotus"],
"lvp"=>["name"=>"Lucent Voice","detail"=>"IANA: Lucent Voice","media"=>"audio","type"=>"vnd.lucent.voice","group"=>"voice"],
"m3u"=>["name"=>"M3U (Multimedia Playlist)","detail"=>"Wikipedia: M3U","media"=>"audio","type"=>"x-mpegurl","group"=>"web"],
"m4v"=>["name"=>"M4v","detail"=>"Wikipedia: M4v","media"=>"video","type"=>"x-m4v","group"=>""],
"hqx"=>["name"=>"Macintosh BinHex 4.0","detail"=>"MacMIME","media"=>"application","type"=>"mac-binhex40","group"=>"apple"],
"portpkg"=>["name"=>"MacPorts Port System","detail"=>"IANA: MacPorts Port System","media"=>"application","type"=>"vnd.macports.portpkg","group"=>"apple"],
"mgp"=>["name"=>"MapGuide DBXML","detail"=>"IANA: MapGuide DBXML","media"=>"application","type"=>"vnd.osgeo.mapguide.package","group"=>"xml"],
"mrc"=>["name"=>"MARC Formats","detail"=>"RFC 2220","media"=>"application","type"=>"marc","group"=>""],
"mrcx"=>["name"=>"MARC21 XML Schema","detail"=>"RFC 6207","media"=>"application","type"=>"marcxml+xml","group"=>"xml"],
"mxf"=>["name"=>"Material Exchange Format","detail"=>"RFC 4539","media"=>"application","type"=>"mxf","group"=>""],
"nbp"=>["name"=>"Mathematica Notebook Player","detail"=>"IANA: Mathematica Notebook Player","media"=>"application","type"=>"vnd.wolfram.player","group"=>""],
"ma"=>["name"=>"Mathematica Notebooks","detail"=>"IANA - Mathematica","media"=>"application","type"=>"mathematica","group"=>"books"],
"mathml"=>["name"=>"Mathematical Markup Language","detail"=>"W3C Math Home","media"=>"application","type"=>"mathml+xml","group"=>""],
"mbox"=>["name"=>"Mbox database files","detail"=>"RFC 4155","media"=>"application","type"=>"mbox","group"=>""],
"mc1"=>["name"=>"MedCalc","detail"=>"IANA: MedCalc","media"=>"application","type"=>"vnd.medcalcdata","group"=>""],
"mscml"=>["name"=>"Media Server Control Markup Language","detail"=>"RFC 5022","media"=>"application","type"=>"mediaservercontrol+xml","group"=>"xml"],
"cdkey"=>["name"=>"MediaRemote","detail"=>"IANA: MediaRemote","media"=>"application","type"=>"vnd.mediastation.cdkey","group"=>""],
"mwf"=>["name"=>"Medical Waveform Encoding Format","detail"=>"IANA: Medical Waveform Encoding Format","media"=>"application","type"=>"vnd.mfer","group"=>""],
"mfm"=>["name"=>"Melody Format for Mobile Platform","detail"=>"IANA: Melody Format for Mobile Platform","media"=>"application","type"=>"vnd.mfmp","group"=>""],
"msh"=>["name"=>"Mesh Data Type","detail"=>"RFC 2077","media"=>"model","type"=>"mesh","group"=>""],
"mads"=>["name"=>"Metadata Authority Description Schema","detail"=>"RFC 6207","media"=>"application","type"=>"mads+xml","group"=>"xml"],
"mets"=>["name"=>"Metadata Encoding and Transmission Standard","detail"=>"RFC 6207","media"=>"application","type"=>"mets+xml","group"=>"xml"],
"mods"=>["name"=>"Metadata Object Description Schema","detail"=>"RFC 6207","media"=>"application","type"=>"mods+xml","group"=>"xml"],
"meta4"=>["name"=>"Metalink","detail"=>"Wikipedia: Metalink","media"=>"application","type"=>"metalink4+xml","group"=>"xml"],
"mcd"=>["name"=>"Micro CADAM Helix D&D","detail"=>"IANA: Micro CADAM Helix D&D","media"=>"application","type"=>"vnd.mcd","group"=>""],
"flo"=>["name"=>"Micrografx","detail"=>"IANA: Micrografx","media"=>"application","type"=>"vnd.micrografx.flo","group"=>""],
"igx"=>["name"=>"Micrografx iGrafx Professional","detail"=>"IANA: Micrografx","media"=>"application","type"=>"vnd.micrografx.igx","group"=>""],
"es3"=>["name"=>"MICROSEC e-Szign¢","detail"=>"IANA: MICROSEC e-Szign¢","media"=>"application","type"=>"vnd.eszigno3+xml","group"=>"xml"],
"mdb"=>["name"=>"Microsoft Access","detail"=>"Wikipedia: Microsoft Access","media"=>"application","type"=>"x-msaccess","group"=>"microsoft"],
"asf"=>["name"=>"Microsoft Advanced Systems Format (ASF)","detail"=>"Wikipedia: Advanced Systems Format (ASF)","media"=>"video","type"=>"x-ms-asf","group"=>"microsoft"],
"exe"=>["name"=>"Microsoft Application","detail"=>"Wikipedia: EXE","media"=>"application","type"=>"x-msdownload","group"=>"microsoft"],
"cil"=>["name"=>"Microsoft Artgalry","detail"=>"IANA: MS Artgalry","media"=>"application","type"=>"vnd.ms-artgalry","group"=>"microsoft"],
"cab"=>["name"=>"Microsoft Cabinet File","detail"=>"IANA: MS Cabinet File","media"=>"application","type"=>"vnd.ms-cab-compressed","group"=>"microsoft"],
"ims"=>["name"=>"Microsoft Class Server","detail"=>"IANA: MS Class Server","media"=>"application","type"=>"vnd.ms-ims","group"=>"microsoft"],
"application"=>["name"=>"Microsoft ClickOnce","detail"=>"Wikipedia: ClickOnce","media"=>"application","type"=>"x-ms-application","group"=>"microsoft"],
"clp"=>["name"=>"Microsoft Clipboard Clip","detail"=>"Wikipedia: Clipboard","media"=>"application","type"=>"x-msclip","group"=>"microsoft"],
"mdi"=>["name"=>"Microsoft Document Imaging Format","detail"=>"Wikipedia: Microsoft Document Image Format","media"=>"image","type"=>"vnd.ms-modi","group"=>"microsoft"],
"eot"=>["name"=>"Microsoft Embedded OpenType","detail"=>"IANA: MS Embedded OpenType","media"=>"application","type"=>"vnd.ms-fontobject","group"=>"microsoft"],
"xls"=>["name"=>"Microsoft Excel","detail"=>"IANA: MS Excel","media"=>"application","type"=>"vnd.ms-excel","group"=>"microsoft"],
"xlam"=>["name"=>"Microsoft Excel - Add-In File","detail"=>"IANA: MS Excel","media"=>"application","type"=>"vnd.ms-excel.addin.macroenabled.12","group"=>"microsoft"],
"xlsb"=>["name"=>"Microsoft Excel - Binary Workbook","detail"=>"IANA: MS Excel","media"=>"application","type"=>"vnd.ms-excel.sheet.binary.macroenabled.12","group"=>"microsoft"],
"xltm"=>["name"=>"Microsoft Excel - Macro-Enabled Template File","detail"=>"IANA: MS Excel","media"=>"application","type"=>"vnd.ms-excel.template.macroenabled.12","group"=>"microsoft"],
"xlsm"=>["name"=>"Microsoft Excel - Macro-Enabled Workbook","detail"=>"IANA: MS Excel","media"=>"application","type"=>"vnd.ms-excel.sheet.macroenabled.12","group"=>"microsoft"],
"chm"=>["name"=>"Microsoft Html Help File","detail"=>"IANA:MS Html Help File","media"=>"application","type"=>"vnd.ms-htmlhelp","group"=>"microsoft"],
"crd"=>["name"=>"Microsoft Information Card","detail"=>"Wikipedia: Information Card","media"=>"application","type"=>"x-mscardfile","group"=>"microsoft"],
"lrm"=>["name"=>"Microsoft Learning Resource Module","detail"=>"IANA: MS Learning Resource Module","media"=>"application","type"=>"vnd.ms-lrm","group"=>"microsoft"],
"mvb"=>["name"=>"Microsoft MediaView","detail"=>"Windows Help","media"=>"application","type"=>"x-msmediaview","group"=>"microsoft"],
"mny"=>["name"=>"Microsoft Money","detail"=>"Wikipedia: Microsoft Money","media"=>"application","type"=>"x-msmoney","group"=>"microsoft"],
"pptx"=>["name"=>"Microsoft Office - OOXML - Presentation","detail"=>"IANA: OOXML - Presentation","media"=>"application","type"=>"vnd.openxmlformats-officedocument.presentationml.presentation","group"=>"microsoft"],
"sldx"=>["name"=>"Microsoft Office - OOXML - Presentation (Slide)","detail"=>"IANA: OOXML - Presentation","media"=>"application","type"=>"vnd.openxmlformats-officedocument.presentationml.slide","group"=>"microsoft"],
"ppsx"=>["name"=>"Microsoft Office - OOXML - Presentation (Slideshow)","detail"=>"IANA: OOXML - Presentation","media"=>"application","type"=>"vnd.openxmlformats-officedocument.presentationml.slideshow","group"=>"microsoft"],
"potx"=>["name"=>"Microsoft Office - OOXML - Presentation Template","detail"=>"IANA: OOXML - Presentation Template","media"=>"application","type"=>"vnd.openxmlformats-officedocument.presentationml.template","group"=>"microsoft"],
"xlsx"=>["name"=>"Microsoft Office - OOXML - Spreadsheet","detail"=>"IANA: OOXML - Spreadsheet","media"=>"application","type"=>"vnd.openxmlformats-officedocument.spreadsheetml.sheet","group"=>"microsoft"],
"xltx"=>["name"=>"Microsoft Office - OOXML - Spreadsheet Template","detail"=>"IANA: OOXML - Spreadsheet Template","media"=>"application","type"=>"vnd.openxmlformats-officedocument.spreadsheetml.template","group"=>"microsoft"],
"docx"=>["name"=>"Microsoft Office - OOXML - Word Document","detail"=>"IANA: OOXML - Word Document","media"=>"application","type"=>"vnd.openxmlformats-officedocument.wordprocessingml.document","group"=>"microsoft"],
"dotx"=>["name"=>"Microsoft Office - OOXML - Word Document Template","detail"=>"IANA: OOXML - Word Document Template","media"=>"application","type"=>"vnd.openxmlformats-officedocument.wordprocessingml.template","group"=>"microsoft"],
"obd"=>["name"=>"Microsoft Office Binder","detail"=>"Wikipedia: Microsoft Shared Tools","media"=>"application","type"=>"x-msbinder","group"=>"microsoft"],
"thmx"=>["name"=>"Microsoft Office System Release Theme","detail"=>"IANA: MS Office System Release Theme","media"=>"application","type"=>"vnd.ms-officetheme","group"=>"microsoft"],
"onetoc"=>["name"=>"Microsoft OneNote","detail"=>"MS OneNote 2010","media"=>"application","type"=>"onenote","group"=>"microsoft"],
"pya"=>["name"=>"Microsoft PlayReady Ecosystem","detail"=>"IANA: Microsoft PlayReady Ecosystem","media"=>"audio","type"=>"vnd.ms-playready.media.pya","group"=>"microsoft"],
"pyv"=>["name"=>"Microsoft PlayReady Ecosystem Video","detail"=>"IANA: Microsoft PlayReady Ecosystem","media"=>"video","type"=>"vnd.ms-playready.media.pyv","group"=>"microsoft"],
"ppt"=>["name"=>"Microsoft PowerPoint","detail"=>"IANA: MS PowerPoint","media"=>"application","type"=>"vnd.ms-powerpoint","group"=>"microsoft"],
"ppam"=>["name"=>"Microsoft PowerPoint - Add-in file","detail"=>"IANA: MS PowerPoint","media"=>"application","type"=>"vnd.ms-powerpoint.addin.macroenabled.12","group"=>"microsoft"],
"sldm"=>["name"=>"Microsoft PowerPoint - Macro-Enabled Open XML Slide","detail"=>"IANA: MS PowerPoint","media"=>"application","type"=>"vnd.ms-powerpoint.slide.macroenabled.12","group"=>"microsoft"],
"pptm"=>["name"=>"Microsoft PowerPoint - Macro-Enabled Presentation File","detail"=>"IANA: MS PowerPoint","media"=>"application","type"=>"vnd.ms-powerpoint.presentation.macroenabled.12","group"=>"microsoft"],
"ppsm"=>["name"=>"Microsoft PowerPoint - Macro-Enabled Slide Show File","detail"=>"IANA: MS PowerPoint","media"=>"application","type"=>"vnd.ms-powerpoint.slideshow.macroenabled.12","group"=>"microsoft"],
"potm"=>["name"=>"Microsoft PowerPoint - Macro-Enabled Template File","detail"=>"IANA: MS PowerPoint","media"=>"application","type"=>"vnd.ms-powerpoint.template.macroenabled.12","group"=>"microsoft"],
"mpp"=>["name"=>"Microsoft Project","detail"=>"IANA: MS PowerPoint","media"=>"application","type"=>"vnd.ms-project","group"=>"microsoft"],
"pub"=>["name"=>"Microsoft Publisher","detail"=>"Wikipedia: Microsoft Publisher","media"=>"application","type"=>"x-mspublisher","group"=>"microsoft"],
"scd"=>["name"=>"Microsoft Schedule+","detail"=>"Wikipedia: Microsoft Schedule Plus","media"=>"application","type"=>"x-msschedule","group"=>"microsoft"],
"xap"=>["name"=>"Microsoft Silverlight","detail"=>"Wikipedia: Silverlight","media"=>"application","type"=>"x-silverlight-app","group"=>"microsoft"],
"stl"=>["name"=>"Microsoft Trust UI Provider - Certificate Trust Link","detail"=>"IANA: MS Trust UI Provider","media"=>"application","type"=>"vnd.ms-pki.stl","group"=>"microsoft"],
"cat"=>["name"=>"Microsoft Trust UI Provider - Security Catalog","detail"=>"IANA: MS Trust UI Provider","media"=>"application","type"=>"vnd.ms-pki.seccat","group"=>"microsoft"],
"vsd"=>["name"=>"Microsoft Visio","detail"=>"IANA: Visio","media"=>"application","type"=>"vnd.visio","group"=>"microsoft"],
"vsdx"=>["name"=>"Microsoft Visio 2013","detail"=>"IANA: Visio","media"=>"application","type"=>"vnd.visio2013","group"=>"microsoft"],
"wm"=>["name"=>"Microsoft Windows Media","detail"=>"Wikipedia: Advanced Systems Format (ASF)","media"=>"video","type"=>"x-ms-wm","group"=>"microsoft"],
"wma"=>["name"=>"Microsoft Windows Media Audio","detail"=>"Wikipedia: Windows Media Audio","media"=>"audio","type"=>"x-ms-wma","group"=>"microsoft"],
"wax"=>["name"=>"Microsoft Windows Media Audio Redirector","detail"=>"Windows Media Metafiles","media"=>"audio","type"=>"x-ms-wax","group"=>"microsoft"],
"wmx"=>["name"=>"Microsoft Windows Media audio","type"=>"Video Playlist","detail"=>"Wikipedia: Advanced Systems Format (ASF)","media"=>"video","type"=>"x-ms-wmx","group"=>"microsoft"],
"wmd"=>["name"=>"Microsoft Windows Media Player Download Package","detail"=>"Wikipedia: Windows Media Player","media"=>"application","type"=>"x-ms-wmd","group"=>"microsoft"],
"wpl"=>["name"=>"Microsoft Windows Media Player Playlist","detail"=>"IANA: MS Windows Media Player Playlist","media"=>"application","type"=>"vnd.ms-wpl","group"=>"microsoft"],
"wmz"=>["name"=>"Microsoft Windows Media Player Skin Package","detail"=>"Wikipedia: Windows Media Player","media"=>"application","type"=>"x-ms-wmz","group"=>"microsoft"],
"wmv"=>["name"=>"Microsoft Windows Media Video","detail"=>"Wikipedia: Advanced Systems Format (ASF)","media"=>"video","type"=>"x-ms-wmv","group"=>"microsoft"],
"wvx"=>["name"=>"Microsoft Windows Media Video Playlist","detail"=>"Wikipedia: Advanced Systems Format (ASF)","media"=>"video","type"=>"x-ms-wvx","group"=>"microsoft"],
"wmf"=>["name"=>"Microsoft Windows Metafile","detail"=>"Wikipedia: Windows Metafile","media"=>"application","type"=>"x-msmetafile","group"=>"microsoft"],
"trm"=>["name"=>"Microsoft Windows Terminal Services","detail"=>"Wikipedia: Terminal Server","media"=>"application","type"=>"x-msterminal","group"=>"microsoft"],
"doc"=>["name"=>"Microsoft Word","detail"=>"Wikipedia: Microsoft Word","media"=>"application","type"=>"msword","group"=>"microsoft"],
"docm"=>["name"=>"Microsoft Word - Macro-Enabled Document","detail"=>"IANA: MS Word","media"=>"application","type"=>"vnd.ms-word.document.macroenabled.12","group"=>"microsoft"],
"dotm"=>["name"=>"Microsoft Word - Macro-Enabled Template","detail"=>"IANA: MS Word","media"=>"application","type"=>"vnd.ms-word.template.macroenabled.12","group"=>"microsoft"],
"wri"=>["name"=>"Microsoft Wordpad","detail"=>"Wikipedia: Wordpad","media"=>"application","type"=>"x-mswrite","group"=>"microsoft"],
"wps"=>["name"=>"Microsoft Works","detail"=>"IANA: MS Works","media"=>"application","type"=>"vnd.ms-works","group"=>"microsoft"],
"xbap"=>["name"=>"Microsoft XAML Browser Application","detail"=>"Wikipedia: XAML Browser","media"=>"application","type"=>"x-ms-xbap","group"=>"microsoft"],
"xps"=>["name"=>"Microsoft XML Paper Specification","detail"=>"IANA: MS XML Paper Specification","media"=>"application","type"=>"vnd.ms-xpsdocument","group"=>"microsoft"],
"mid"=>["name"=>"MIDI - Musical Instrument Digital Interface","detail"=>"Wikipedia: MIDI","media"=>"audio","type"=>"midi","group"=>""],
"mpy"=>["name"=>"MiniPay","detail"=>"IANA: MiniPay","media"=>"application","type"=>"vnd.ibm.minipay","group"=>""],
"afp"=>["name"=>"MO:DCA-P","detail"=>"IANA: MO:DCA-P","media"=>"application","type"=>"vnd.ibm.modcap","group"=>""],
"rms"=>["name"=>"Mobile Information Device Profile","detail"=>"IANA: Mobile Information Device Profile","media"=>"application","type"=>"vnd.jcp.javame.midlet-rms","group"=>""],
"tmo"=>["name"=>"MobileTV","detail"=>"IANA: MobileTV","media"=>"application","type"=>"vnd.tmobile-livetv","group"=>""],
"prc"=>["name"=>"Mobipocket","detail"=>"Wikipedia: Mobipocket","media"=>"application","type"=>"x-mobipocket-ebook","group"=>""],
"mbk"=>["name"=>"Mobius Management Systems - Basket file","detail"=>"IANA: Mobius Management Systems","media"=>"application","type"=>"vnd.mobius.mbk","group"=>""],
"dis"=>["name"=>"Mobius Management Systems - Distribution Database","detail"=>"IANA: Mobius Management Systems","media"=>"application","type"=>"vnd.mobius.dis","group"=>""],
"plc"=>["name"=>"Mobius Management Systems - Policy Definition Language File","detail"=>"IANA: Mobius Management Systems","media"=>"application","type"=>"vnd.mobius.plc","group"=>""],
"mqy"=>["name"=>"Mobius Management Systems - Query File","detail"=>"IANA: Mobius Management Systems","media"=>"application","type"=>"vnd.mobius.mqy","group"=>""],
"msl"=>["name"=>"Mobius Management Systems - Script Language","detail"=>"IANA: Mobius Management Systems","media"=>"application","type"=>"vnd.mobius.msl","group"=>""],
"txf"=>["name"=>"Mobius Management Systems - Topic Index File","detail"=>"IANA: Mobius Management Systems","media"=>"application","type"=>"vnd.mobius.txf","group"=>""],
"daf"=>["name"=>"Mobius Management Systems - UniversalArchive","detail"=>"IANA: Mobius Management Systems","media"=>"application","type"=>"vnd.mobius.daf","group"=>""],
"fly"=>["name"=>"mod_fly / fly.cgi","detail"=>"IANA: Fly","media"=>"text","type"=>"vnd.fly","group"=>""],
"mpc"=>["name"=>"Mophun Certificate","detail"=>"IANA: Mophun Certificate","media"=>"application","type"=>"vnd.mophun.certificate","group"=>""],
"mpn"=>["name"=>"Mophun VM","detail"=>"IANA: Mophun VM","media"=>"application","type"=>"vnd.mophun.application","group"=>""],
"mj2"=>["name"=>"Motion JPEG 2000","detail"=>"IANA: MJ2","media"=>"video","type"=>"mj2","group"=>""],
"mpga"=>["name"=>"MPEG Audio","detail"=>"Wikipedia: MPGA","media"=>"audio","type"=>"mpeg","group"=>"mpeg"],
"mxu"=>["name"=>"MPEG Url","detail"=>"IANA: MPEG Url","media"=>"video","type"=>"vnd.mpegurl","group"=>"mpeg"],
"mpeg"=>["name"=>"MPEG Video","detail"=>"Wikipedia: MPEG","media"=>"video","type"=>"mpeg","group"=>"mpeg"],
"m21"=>["name"=>"MPEG-21","detail"=>"Wikipedia: MPEG-21","media"=>"application","type"=>"mp21","group"=>"mpeg"],
"mp4a"=>["name"=>"MPEG-4 Audio","detail"=>"Wikipedia: MP4A","media"=>"audio","type"=>"mp4","group"=>"mpeg"],
"mp4"=>["name"=>"MPEG-4 Video","detail"=>"Wikipedia: MP4","media"=>"video","type"=>"mp4","group"=>"mpeg"],
"mp4"=>["name"=>"MPEG4","detail"=>"RFC 4337","media"=>"application","type"=>"mp4","group"=>"mpeg"],
"m3u8"=>["name"=>"Multimedia Playlist Unicode","detail"=>"Wikipedia: M3U","media"=>"application","type"=>"vnd.apple.mpegurl","group"=>""],
"mus"=>["name"=>"MUsical Score Interpreted Code Invented for the ASCII designation of Notation","detail"=>"IANA: MUSICIAN","media"=>"application","type"=>"vnd.musician","group"=>"music"],
"msty"=>["name"=>"Muvee Automatic Video Editing","detail"=>"IANA: Muvee","media"=>"application","type"=>"vnd.muvee.style","group"=>""],
"mxml"=>["name"=>"MXML","detail"=>"Wikipedia: MXML","media"=>"application","type"=>"xv+xml","group"=>"xml"],
"ngdat"=>["name"=>"N-Gage Game Data","detail"=>"IANA: N-Gage Game Data","media"=>"application","type"=>"vnd.nokia.n-gage.data","group"=>""],
"n-gage"=>["name"=>"N-Gage Game Installer","detail"=>"IANA: N-Gage Game Installer","media"=>"application","type"=>"vnd.nokia.n-gage.symbian.install","group"=>""],
"ncx"=>["name"=>"Navigation Control file for XML (for ePub)","detail"=>"Wikipedia: EPUB","media"=>"application","type"=>"x-dtbncx+xml","group"=>""],
"nc"=>["name"=>"Network Common Data Form (NetCDF)","detail"=>"Wikipedia: NetCDF","media"=>"application","type"=>"x-netcdf","group"=>""],
"nlu"=>["name"=>"neuroLanguage","detail"=>"IANA: neuroLanguage","media"=>"application","type"=>"vnd.neurolanguage.nlu","group"=>""],
"dna"=>["name"=>"New Moon Liftoff/DNA","detail"=>"IANA: New Moon Liftoff/DNA","media"=>"application","type"=>"vnd.dna","group"=>""],
"nnd"=>["name"=>"NobleNet Directory","detail"=>"IANA: NobleNet Directory","media"=>"application","type"=>"vnd.noblenet-directory","group"=>""],
"nns"=>["name"=>"NobleNet Sealer","detail"=>"IANA: NobleNet Sealer","media"=>"application","type"=>"vnd.noblenet-sealer","group"=>""],
"nnw"=>["name"=>"NobleNet Web","detail"=>"IANA: NobleNet Web","media"=>"application","type"=>"vnd.noblenet-web","group"=>""],
"rpst"=>["name"=>"Nokia Radio Application - Preset","detail"=>"IANA: Nokia Radio Application","media"=>"application","type"=>"vnd.nokia.radio-preset","group"=>""],
"rpss"=>["name"=>"Nokia Radio Application - Preset","detail"=>"IANA: Nokia Radio Application","media"=>"application","type"=>"vnd.nokia.radio-presets","group"=>""],
"n3"=>["name"=>"Notation3","detail"=>"Wikipedia: Notation3","media"=>"text","type"=>"n3","group"=>""],
"edm"=>["name"=>"Novadigm's RADIA and EDM products","detail"=>"IANA: Novadigm's RADIA and EDM products","media"=>"application","type"=>"vnd.novadigm.edm","group"=>""],
"edx"=>["name"=>"Novadigm's RADIA and EDM products","detail"=>"IANA: Novadigm's RADIA and EDM products","media"=>"application","type"=>"vnd.novadigm.edx","group"=>""],
"ext"=>["name"=>"Novadigm's RADIA and EDM products","detail"=>"IANA: Novadigm's RADIA and EDM products","media"=>"application","type"=>"vnd.novadigm.ext","group"=>""],
"gph"=>["name"=>"NpGraphIt","detail"=>"IANA: FloGraphIt","media"=>"application","type"=>"vnd.flographit","group"=>"graphic"],
"ecelp4800"=>["name"=>"Nuera ECELP 4800","detail"=>"IANA: ECELP 4800","media"=>"audio","type"=>"vnd.nuera.ecelp4800","group"=>""],
"ecelp7470"=>["name"=>"Nuera ECELP 7470","detail"=>"IANA: ECELP 7470","media"=>"audio","type"=>"vnd.nuera.ecelp7470","group"=>""],
"ecelp9600"=>["name"=>"Nuera ECELP 9600","detail"=>"IANA: ECELP 9600","media"=>"audio","type"=>"vnd.nuera.ecelp9600","group"=>""],
"oda"=>["name"=>"Office Document Architecture","detail"=>"RFC 2161","media"=>"application","type"=>"oda","group"=>"ogg"],
"ogx"=>["name"=>"Ogg","detail"=>"Wikipedia: Ogg","media"=>"application","type"=>"ogg","group"=>"ogg"],
"oga"=>["name"=>"Ogg Audio","detail"=>"Wikipedia: Ogg","media"=>"audio","type"=>"ogg","group"=>"ogg"],
"ogv"=>["name"=>"Ogg Video","detail"=>"Wikipedia: Ogg","media"=>"video","type"=>"ogg","group"=>"ogg"],
"dd2"=>["name"=>"OMA Download Agents","detail"=>"IANA: OMA Download Agents","media"=>"application","type"=>"vnd.oma.dd2+xml","group"=>""],
"oth"=>["name"=>"Open Document Text Web","detail"=>"IANA: OpenDocument Text Web","media"=>"application","type"=>"vnd.oasis.opendocument.text-web","group"=>""],
"opf"=>["name"=>"Open eBook Publication Structure","detail"=>"Wikipedia: Open eBook","media"=>"application","type"=>"oebps-package+xml","group"=>"book"],
"qbo"=>["name"=>"Open Financial Exchange","detail"=>"IANA: Open Financial Exchange","media"=>"application","type"=>"vnd.intu.qbo","group"=>""],
"oxt"=>["name"=>"Open Office Extension","detail"=>"IANA: Open Office Extension","media"=>"application","type"=>"vnd.openofficeorg.extension","group"=>""],
"osf"=>["name"=>"Open Score Format","detail"=>"IANA: Open Score Format","media"=>"application","type"=>"vnd.yamaha.openscoreformat","group"=>""],
"weba"=>["name"=>"Open Web Media Project - Audio","detail"=>"WebM Project","media"=>"audio","type"=>"webm","group"=>"web"],
"webm"=>["name"=>"Open Web Media Project - Video","detail"=>"WebM Project","media"=>"video","type"=>"webm","group"=>"web"],
"odc"=>["name"=>"OpenDocument Chart","detail"=>"IANA: OpenDocument Chart","media"=>"application","type"=>"vnd.oasis.opendocument.chart","group"=>"opendocument"],
"otc"=>["name"=>"OpenDocument Chart Template","detail"=>"IANA: OpenDocument Chart Template","media"=>"application","type"=>"vnd.oasis.opendocument.chart-template","group"=>"opendocument"],
"odb"=>["name"=>"OpenDocument Database","detail"=>"IANA: OpenDocument Database","media"=>"application","type"=>"vnd.oasis.opendocument.database","group"=>"opendocument"],
"odf"=>["name"=>"OpenDocument Formula","detail"=>"IANA: OpenDocument Formula","media"=>"application","type"=>"vnd.oasis.opendocument.formula","group"=>"opendocument"],
"odft"=>["name"=>"OpenDocument Formula Template","detail"=>"IANA: OpenDocument Formula Template","media"=>"application","type"=>"vnd.oasis.opendocument.formula-template","group"=>"opendocument"],
"odg"=>["name"=>"OpenDocument Graphics","detail"=>"IANA: OpenDocument Graphics","media"=>"application","type"=>"vnd.oasis.opendocument.graphics","group"=>"opendocument"],
"otg"=>["name"=>"OpenDocument Graphics Template","detail"=>"IANA: OpenDocument Graphics Template","media"=>"application","type"=>"vnd.oasis.opendocument.graphics-template","group"=>"opendocument"],
"odi"=>["name"=>"OpenDocument Image","detail"=>"IANA: OpenDocument Image","media"=>"application","type"=>"vnd.oasis.opendocument.image","group"=>"opendocument"],
"oti"=>["name"=>"OpenDocument Image Template","detail"=>"IANA: OpenDocument Image Template","media"=>"application","type"=>"vnd.oasis.opendocument.image-template","group"=>"opendocument"],
"odp"=>["name"=>"OpenDocument Presentation","detail"=>"IANA: OpenDocument Presentation","media"=>"application","type"=>"vnd.oasis.opendocument.presentation","group"=>"opendocument"],
"otp"=>["name"=>"OpenDocument Presentation Template","detail"=>"IANA: OpenDocument Presentation Template","media"=>"application","type"=>"vnd.oasis.opendocument.presentation-template","group"=>"opendocument"],
"ods"=>["name"=>"OpenDocument Spreadsheet","detail"=>"IANA: OpenDocument Spreadsheet","media"=>"application","type"=>"vnd.oasis.opendocument.spreadsheet","group"=>"opendocument"],
"ots"=>["name"=>"OpenDocument Spreadsheet Template","detail"=>"IANA: OpenDocument Spreadsheet Template","media"=>"application","type"=>"vnd.oasis.opendocument.spreadsheet-template","group"=>"opendocument"],
"odt"=>["name"=>"OpenDocument Text","detail"=>"IANA: OpenDocument Text","media"=>"application","type"=>"vnd.oasis.opendocument.text","group"=>"opendocument"],
"odm"=>["name"=>"OpenDocument Text Master","detail"=>"IANA: OpenDocument Text Master","media"=>"application","type"=>"vnd.oasis.opendocument.text-master","group"=>"opendocument"],
"ott"=>["name"=>"OpenDocument Text Template","detail"=>"IANA: OpenDocument Text Template","media"=>"application","type"=>"vnd.oasis.opendocument.text-template","group"=>"opendocument"],
"ktx"=>["name"=>"OpenGL Textures (KTX)","detail"=>"KTX File Format","media"=>"image","type"=>"ktx","group"=>"graphic"],
"sxc"=>["name"=>"OpenOffice - Calc (Spreadsheet)","detail"=>"Wikipedia: OpenOffice","media"=>"application","type"=>"vnd.sun.xml.calc","group"=>"openoffice"],
"stc"=>["name"=>"OpenOffice - Calc Template (Spreadsheet)","detail"=>"Wikipedia: OpenOffice","media"=>"application","type"=>"vnd.sun.xml.calc.template","group"=>"openoffice"],
"sxd"=>["name"=>"OpenOffice - Draw (Graphics)","detail"=>"Wikipedia: OpenOffice","media"=>"application","type"=>"vnd.sun.xml.draw","group"=>"openoffice"],
"std"=>["name"=>"OpenOffice - Draw Template (Graphics)","detail"=>"Wikipedia: OpenOffice","media"=>"application","type"=>"vnd.sun.xml.draw.template","group"=>"openoffice"],
"sxi"=>["name"=>"OpenOffice - Impress (Presentation)","detail"=>"Wikipedia: OpenOffice","media"=>"application","type"=>"vnd.sun.xml.impress","group"=>"openoffice"],
"sti"=>["name"=>"OpenOffice - Impress Template (Presentation)","detail"=>"Wikipedia: OpenOffice","media"=>"application","type"=>"vnd.sun.xml.impress.template","group"=>"openoffice"],
"sxm"=>["name"=>"OpenOffice - Math (Formula)","detail"=>"Wikipedia: OpenOffice","media"=>"application","type"=>"vnd.sun.xml.math","group"=>"openoffice"],
"sxw"=>["name"=>"OpenOffice - Writer (Text - HTML)","detail"=>"Wikipedia: OpenOffice","media"=>"application","type"=>"vnd.sun.xml.writer","group"=>"openoffice"],
"sxg"=>["name"=>"OpenOffice - Writer (Text - HTML)","detail"=>"Wikipedia: OpenOffice","media"=>"application","type"=>"vnd.sun.xml.writer.global","group"=>"openoffice"],
"stw"=>["name"=>"OpenOffice - Writer Template (Text - HTML)","detail"=>"Wikipedia: OpenOffice","media"=>"application","type"=>"vnd.sun.xml.writer.template","group"=>"openoffice"],
"otf"=>["name"=>"OpenType Font File","detail"=>"OpenType Font File","media"=>"application","type"=>"x-font-otf","group"=>"font"],
"osfpvg"=>["name"=>"OSFPVG","detail"=>"IANA: OSFPVG","media"=>"application","type"=>"vnd.yamaha.openscoreformat.osfpvg+xml","group"=>""],
"dp"=>["name"=>"OSGi Deployment Package","detail"=>"IANA: OSGi Deployment Package","media"=>"application","type"=>"vnd.osgi.dp","group"=>""],
"pdb"=>["name"=>"PalmOS Data","detail"=>"IANA: PalmOS Data","media"=>"application","type"=>"vnd.palm","group"=>""],
"p"=>["name"=>"Pascal Source File","detail"=>"Wikipedia: Pascal","media"=>"text","type"=>"x-pascal","group"=>""],
"paw"=>["name"=>"PawaaFILE","detail"=>"IANA: PawaaFILE","media"=>"application","type"=>"vnd.pawaafile","group"=>""],
"pclxl"=>["name"=>"PCL 6 Enhanced (Formely PCL XL)","detail"=>"IANA: HP PCL XL","media"=>"application","type"=>"vnd.hp-pclxl","group"=>""],
"efif"=>["name"=>"Pcsel eFIF File","detail"=>"IANA: Picsel eFIF File","media"=>"application","type"=>"vnd.picsel","group"=>""],
"pcx"=>["name"=>"PCX Image","detail"=>"Wikipedia: PCX","media"=>"image","type"=>"x-pcx","group"=>""],
"psd"=>["name"=>"Photoshop Document","detail"=>"Wikipedia: Photoshop Document","media"=>"image","type"=>"vnd.adobe.photoshop","group"=>"adobe"],
"prf"=>["name"=>"PICSRules","detail"=>"W3C PICSRules","media"=>"application","type"=>"pics-rules","group"=>""],
"pic"=>["name"=>"PICT Image","detail"=>"Wikipedia: PICT","media"=>"image","type"=>"x-pict","group"=>""],
"chat"=>["name"=>"pIRCh","detail"=>"Wikipedia: pIRCh","media"=>"application","type"=>"x-chat","group"=>""],
"p10"=>["name"=>"PKCS #10 - Certification Request Standard","detail"=>"RFC 2986","media"=>"application","type"=>"pkcs10","group"=>"cryptographic"],
"p12"=>["name"=>"PKCS #12 - Personal Information Exchange Syntax Standard","detail"=>"RFC 2986","media"=>"application","type"=>"x-pkcs12","group"=>"cryptographic"],
"p7m"=>["name"=>"PKCS #7 - Cryptographic Message Syntax Standard","detail"=>"RFC 2315","media"=>"application","type"=>"pkcs7-mime","group"=>"cryptographic"],
"p7s"=>["name"=>"PKCS #7 - Cryptographic Message Syntax Standard","detail"=>"RFC 2315","media"=>"application","type"=>"pkcs7-signature","group"=>"cryptographic"],
"p7r"=>["name"=>"PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)","detail"=>"RFC 2986","media"=>"application","type"=>"x-pkcs7-certreqresp","group"=>"cryptographic"],
"p7b"=>["name"=>"PKCS #7 - Cryptographic Message Syntax Standard (Certificates)","detail"=>"RFC 2986","media"=>"application","type"=>"x-pkcs7-certificates","group"=>"cryptographic"],
"p8"=>["name"=>"PKCS #8 - Private-Key Information Syntax Standard","detail"=>"RFC 5208","media"=>"application","type"=>"pkcs8","group"=>"cryptographic"],
"plf"=>["name"=>"PocketLearn Viewers","detail"=>"IANA: PocketLearn Viewers","media"=>"application","type"=>"vnd.pocketlearn","group"=>""],
"pnm"=>["name"=>"Portable Anymap Image","detail"=>"Wikipedia: Netpbm Format","media"=>"image","type"=>"x-portable-anymap","group"=>""],
"pbm"=>["name"=>"Portable Bitmap Format","detail"=>"Wikipedia: Netpbm Format","media"=>"image","type"=>"x-portable-bitmap","group"=>""],
"pcf"=>["name"=>"Portable Compiled Format","detail"=>"Wikipedia: Portable Compiled Format","media"=>"application","type"=>"x-font-pcf","group"=>"font"],
"pfr"=>["name"=>"Portable Font Resource","detail"=>"RFC 3073","media"=>"application","type"=>"font-tdpfr","group"=>"font"],
"pgn"=>["name"=>"Portable Game Notation (Chess Games)","detail"=>"Wikipedia: Portable Game Notationb","media"=>"application","type"=>"x-chess-pgn","group"=>""],
"pgm"=>["name"=>"Portable Graymap Format","detail"=>"Wikipedia: Netpbm Format","media"=>"image","type"=>"x-portable-graymap","group"=>""],
"png"=>["name"=>"Portable Network Graphics (PNG)","detail"=>"RFC 2083","media"=>"image","type"=>"png","group"=>""],
"png"=>["name"=>"Portable Network Graphics (PNG) (Citrix client)","detail"=>"RFC 2083","media"=>"image","type"=>"x-citrix-png","group"=>""],
"png"=>["name"=>"Portable Network Graphics (PNG) (x-token)","detail"=>"RFC 2083","media"=>"image","type"=>"x-png","group"=>""],
"ppm"=>["name"=>"Portable Pixmap Format","detail"=>"Wikipedia: Netpbm Format","media"=>"image","type"=>"x-portable-pixmap","group"=>""],
"pskcxml"=>["name"=>"Portable Symmetric Key Container","detail"=>"RFC 6030","media"=>"application","type"=>"pskc+xml","group"=>""],
"pml"=>["name"=>"PosML","detail"=>"IANA: PosML","media"=>"application","type"=>"vnd.ctc-posml","group"=>""],
"ai"=>["name"=>"PostScript","detail"=>"Wikipedia: PostScript","media"=>"application","type"=>"postscript","group"=>"font"],
"pfa"=>["name"=>"PostScript Fonts","detail"=>"Wikipedia: PostScript Fonts","media"=>"application","type"=>"x-font-type1","group"=>"font"],
"pbd"=>["name"=>"PowerBuilder","detail"=>"IANA: PowerBuilder","media"=>"application","type"=>"vnd.powerbuilder6","group"=>""],
"pgp"=>["name"=>"Pretty Good Privacy","detail"=>"RFC 2015","media"=>"application","type"=>"pgp-encrypted","group"=>""],
"pgp"=>["name"=>"Pretty Good Privacy - Signature","detail"=>"RFC 2015","media"=>"application","type"=>"pgp-signature","group"=>""],
"box"=>["name"=>"Preview Systems ZipLock/VBox","detail"=>"IANA: Preview Systems ZipLock/Vbox","media"=>"application","type"=>"vnd.previewsystems.box","group"=>""],
"ptid"=>["name"=>"Princeton Video Image","detail"=>"IANA: Princeton Video Image","media"=>"application","type"=>"vnd.pvi.ptid1","group"=>""],
"pls"=>["name"=>"Pronunciation Lexicon Specification","detail"=>"RFC 4267","media"=>"application","type"=>"pls+xml","group"=>""],
"str"=>["name"=>"Proprietary P&G Standard Reporting System","detail"=>"IANA: Proprietary P&G Standard Reporting System","media"=>"application","type"=>"vnd.pg.format","group"=>""],
"ei6"=>["name"=>"Proprietary P&G Standard Reporting System","detail"=>"IANA: Proprietary P&G Standard Reporting System","media"=>"application","type"=>"vnd.pg.osasli","group"=>""],
"dsc"=>["name"=>"PRS Lines Tag","detail"=>"IANA: PRS Lines Tag","media"=>"text","type"=>"prs.lines.tag","group"=>""],
"psf"=>["name"=>"PSF Fonts","detail"=>"PSF Fonts","media"=>"application","type"=>"x-font-linux-psf","group"=>"font"],
"qps"=>["name"=>"PubliShare Objects","detail"=>"IANA: PubliShare Objects","media"=>"application","type"=>"vnd.publishare-delta-tree","group"=>""],
"wg"=>["name"=>"Qualcomm's Plaza Mobile Internet","detail"=>"IANA: Qualcomm's Plaza Mobile Internet","media"=>"application","type"=>"vnd.pmi.widget","group"=>""],
"qxd"=>["name"=>"QuarkXpress","detail"=>"IANA: QuarkXPress","media"=>"application","type"=>"vnd.quark.quarkxpress","group"=>""],
"esf"=>["name"=>"QUASS Stream Player","detail"=>"IANA: QUASS Stream Player","media"=>"application","type"=>"vnd.epson.esf","group"=>""],
"msf"=>["name"=>"QUASS Stream Player","detail"=>"IANA: QUASS Stream Player","media"=>"application","type"=>"vnd.epson.msf","group"=>""],
"ssf"=>["name"=>"QUASS Stream Player","detail"=>"IANA: QUASS Stream Player","media"=>"application","type"=>"vnd.epson.ssf","group"=>""],
"qam"=>["name"=>"QuickAnime Player","detail"=>"IANA: QuickAnime Player","media"=>"application","type"=>"vnd.epson.quickanime","group"=>""],
"qfx"=>["name"=>"Quicken","detail"=>"IANA: Quicken","media"=>"application","type"=>"vnd.intu.qfx","group"=>""],
"qt"=>["name"=>"Quicktime Video","detail"=>"Wikipedia: Quicktime","media"=>"video","type"=>"quicktime","group"=>"apple"],
"rar"=>["name"=>"RAR Archive","detail"=>"Wikipedia: RAR","media"=>"application","type"=>"x-rar-compressed","group"=>"compress"],
"ram"=>["name"=>"Real Audio Sound","detail"=>"Wikipedia: RealPlayer","media"=>"audio","type"=>"x-pn-realaudio","group"=>""],
"rmp"=>["name"=>"Real Audio Sound","detail"=>"Wikipedia: RealPlayer","media"=>"audio","type"=>"x-pn-realaudio-plugin","group"=>""],
"rsd"=>["name"=>"Really Simple Discovery","detail"=>"Wikipedia: Really Simple Discovery","media"=>"application","type"=>"rsd+xml","group"=>""],
"rm"=>["name"=>"RealMedia","detail"=>"","media"=>"application","type"=>"vnd.rn-realmedia","group"=>""],
"bed"=>["name"=>"RealVNC","detail"=>"IANA: RealVNC","media"=>"application","type"=>"vnd.realvnc.bed","group"=>"linux"],
"mxl"=>["name"=>"Recordare Applications","detail"=>"IANA: Recordare Apps","media"=>"application","type"=>"vnd.recordare.musicxml","group"=>""],
"musicxml"=>["name"=>"Recordare Applications","detail"=>"IANA: Recordare Apps","media"=>"application","type"=>"vnd.recordare.musicxml+xml","group"=>"xml"],
"rnc"=>["name"=>"Relax NG Compact Syntax","detail"=>"Relax NG","media"=>"application","type"=>"relax-ng-compact-syntax","group"=>""],
"rdz"=>["name"=>"RemoteDocs R-Viewer","detail"=>"IANA: Data-Vision","media"=>"application","type"=>"vnd.data-vision.rdz","group"=>""],
"rdf"=>["name"=>"Resource Description Framework","detail"=>"RFC 3870","media"=>"application","type"=>"rdf+xml","group"=>""],
"rp9"=>["name"=>"RetroPlatform Player","detail"=>"IANA: RetroPlatform Player","media"=>"application","type"=>"vnd.cloanto.rp9","group"=>""],
"jisp"=>["name"=>"RhymBox","detail"=>"IANA: RhymBox","media"=>"application","type"=>"vnd.jisp","group"=>""],
"rtf"=>["name"=>"Rich Text Format","detail"=>"Wikipedia: Rich Text Format","media"=>"application","type"=>"rtf","group"=>""],
"rtx"=>["name"=>"Rich Text Format (RTF)","detail"=>"Wikipedia: Rich Text Format","media"=>"text","type"=>"richtext","group"=>""],
"link66"=>["name"=>"ROUTE 66 Location Based Services","detail"=>"IANA: ROUTE 66","media"=>"application","type"=>"vnd.route66.link66+xml","group"=>"xml"],
"rss"=>["name"=>"RSS - Really Simple Syndication","detail"=>"Wikipedia: RSS","media"=>"application","type"=>"rss+xml","group"=>"xml"],
"shf"=>["name"=>"S Hexdump Format","detail"=>"RFC 4194","media"=>"application","type"=>"shf+xml","group"=>"xml"],
"st"=>["name"=>"SailingTracker","detail"=>"IANA: SailingTracker","media"=>"application","type"=>"vnd.sailingtracker.track","group"=>""],
"svg"=>["name"=>"Scalable Vector Graphics (SVG)","detail"=>"Wikipedia: SVG","media"=>"image","type"=>"svg+xml","group"=>"graphic"],
"sus"=>["name"=>"ScheduleUs","detail"=>"IANA: ScheduleUs","media"=>"application","type"=>"vnd.sus-calendar","group"=>""],
"sru"=>["name"=>"Search/Retrieve via URL Response Format","detail"=>"RFC 6207","media"=>"application","type"=>"sru+xml","group"=>""],
"setpay"=>["name"=>"Secure Electronic Transaction - Payment","detail"=>"IANA: SET Payment","media"=>"application","type"=>"set-payment-initiation","group"=>"cryptographic"],
"setreg"=>["name"=>"Secure Electronic Transaction - Registration","detail"=>"IANA: SET Registration","media"=>"application","type"=>"set-registration-initiation","group"=>"cryptographic"],
"sema"=>["name"=>"Secured eMail","detail"=>"IANA: Secured eMail","media"=>"application","type"=>"vnd.sema","group"=>"cryptographic"],
"semd"=>["name"=>"Secured eMail","detail"=>"IANA: Secured eMail","media"=>"application","type"=>"vnd.semd","group"=>"cryptographic"],
"semf"=>["name"=>"Secured eMail","detail"=>"IANA: Secured eMail","media"=>"application","type"=>"vnd.semf","group"=>"cryptographic"],
"see"=>["name"=>"SeeMail","detail"=>"IANA: SeeMail","media"=>"application","type"=>"vnd.seemail","group"=>"web"],
"snf"=>["name"=>"Server Normal Format","detail"=>"Wikipedia: Server Normal Format","media"=>"application","type"=>"x-font-snf","group"=>"font"],
"spq"=>["name"=>"Server-Based Certificate Validation Protocol - Validation Policies - Request","detail"=>"RFC 5055","media"=>"application","type"=>"scvp-vp-request","group"=>"cryptographic"],
"spp"=>["name"=>"Server-Based Certificate Validation Protocol - Validation Policies - Response","detail"=>"RFC 5055","media"=>"application","type"=>"scvp-vp-response","group"=>"cryptographic"],
"scq"=>["name"=>"Server-Based Certificate Validation Protocol - Validation Request","detail"=>"RFC 5055","media"=>"application","type"=>"scvp-cv-request","group"=>"cryptographic"],
"scs"=>["name"=>"Server-Based Certificate Validation Protocol - Validation Response","detail"=>"RFC 5055","media"=>"application","type"=>"scvp-cv-response","group"=>"cryptographic"],
"sdp"=>["name"=>"Session Description Protocol","detail"=>"RFC 2327","media"=>"application","type"=>"sdp","group"=>"cryptographic"],
"etx"=>["name"=>"Setext","detail"=>"Wikipedia: Setext","media"=>"text","type"=>"x-setext","group"=>""],
"movie"=>["name"=>"SGI Movie","detail"=>"SGI Facts","media"=>"video","type"=>"x-sgi-movie","group"=>""],
"ifm"=>["name"=>"Shana Informed Filler","detail"=>"IANA: Shana Informed Filler","media"=>"application","type"=>"vnd.shana.informed.formdata","group"=>""],
"itp"=>["name"=>"Shana Informed Filler","detail"=>"IANA: Shana Informed Filler","media"=>"application","type"=>"vnd.shana.informed.formtemplate","group"=>""],
"iif"=>["name"=>"Shana Informed Filler","detail"=>"IANA: Shana Informed Filler","media"=>"application","type"=>"vnd.shana.informed.interchange","group"=>""],
"ipk"=>["name"=>"Shana Informed Filler","detail"=>"IANA: Shana Informed Filler","media"=>"application","type"=>"vnd.shana.informed.package","group"=>""],
"tfi"=>["name"=>"Sharing Transaction Fraud Data","detail"=>"RFC 5941","media"=>"application","type"=>"thraud+xml","group"=>""],
"shar"=>["name"=>"Shell Archive","detail"=>"Wikipedia: Shell Archie","media"=>"application","type"=>"x-shar","group"=>""],
"rgb"=>["name"=>"Silicon Graphics RGB Bitmap","detail"=>"RGB Image Format","media"=>"image","type"=>"x-rgb","group"=>"graphic"],
"slt"=>["name"=>"SimpleAnimeLite Player","detail"=>"IANA: SimpleAnimeLite Player","media"=>"application","type"=>"vnd.epson.salt","group"=>""],
"aso"=>["name"=>"Simply Accounting","detail"=>"IANA: Simply Accounting","media"=>"application","type"=>"vnd.accpac.simply.aso","group"=>""],
"imp"=>["name"=>"Simply Accounting - Data Import","detail"=>"IANA: Simply Accounting","media"=>"application","type"=>"vnd.accpac.simply.imp","group"=>""],
"twd"=>["name"=>"SimTech MindMapper","detail"=>"IANA: SimTech MindMapper","media"=>"application","type"=>"vnd.simtech-mindmapper","group"=>""],
"csp"=>["name"=>"Sixth Floor Media - CommonSpace","detail"=>"IANA: CommonSpace","media"=>"application","type"=>"vnd.commonspace","group"=>""],
"saf"=>["name"=>"SMAF Audio","detail"=>"IANA: SMAF Audio","media"=>"application","type"=>"vnd.yamaha.smaf-audio","group"=>""],
"mmf"=>["name"=>"SMAF File","detail"=>"IANA: SMAF File","media"=>"application","type"=>"vnd.smaf","group"=>""],
"spf"=>["name"=>"SMAF Phrase","detail"=>"IANA: SMAF Phrase","media"=>"application","type"=>"vnd.yamaha.smaf-phrase","group"=>""],
"teacher"=>["name"=>"SMART Technologies Apps","detail"=>"IANA: SMART Technologies Apps","media"=>"application","type"=>"vnd.smart.teacher","group"=>""],
"svd"=>["name"=>"SourceView Document","detail"=>"IANA: SourceView Document","media"=>"application","type"=>"vnd.svd","group"=>""],
"rq"=>["name"=>"SPARQL - Query","detail"=>"W3C SPARQL","media"=>"application","type"=>"sparql-query","group"=>""],
"srx"=>["name"=>"SPARQL - Results","detail"=>"W3C SPARQL","media"=>"application","type"=>"sparql-results+xml","group"=>""],
"gram"=>["name"=>"Speech Recognition Grammar Specification","detail"=>"W3C Speech Grammar","media"=>"application","type"=>"srgs","group"=>""],
"grxml"=>["name"=>"Speech Recognition Grammar Specification - XML","detail"=>"W3C Speech Grammar","media"=>"application","type"=>"srgs+xml","group"=>"xml"],
"ssml"=>["name"=>"Speech Synthesis Markup Language","detail"=>"W3C Speech Synthesis","media"=>"application","type"=>"ssml+xml","group"=>"xml"],
"skp"=>["name"=>"SSEYO Koan Play File","detail"=>"IANA: SSEYO Koan Play File","media"=>"application","type"=>"vnd.koan","group"=>""],
"sgml"=>["name"=>"Standard Generalized Markup Language (SGML)","detail"=>"Wikipedia: SGML","media"=>"text","type"=>"sgml","group"=>""],
"sdc"=>["name"=>"StarOffice - Calc","detail"=>"","media"=>"application","type"=>"vnd.stardivision.calc","group"=>"staroffice"],
"sda"=>["name"=>"StarOffice - Draw","detail"=>"","media"=>"application","type"=>"vnd.stardivision.draw","group"=>"staroffice"],
"sdd"=>["name"=>"StarOffice - Impress","detail"=>"","media"=>"application","type"=>"vnd.stardivision.impress","group"=>"staroffice"],
"smf"=>["name"=>"StarOffice - Math","detail"=>"","media"=>"application","type"=>"vnd.stardivision.math","group"=>"staroffice"],
"sdw"=>["name"=>"StarOffice - Writer","detail"=>"","media"=>"application","type"=>"vnd.stardivision.writer","group"=>"staroffice"],
"sgl"=>["name"=>"StarOffice - Writer (Global)","detail"=>"","media"=>"application","type"=>"vnd.stardivision.writer-global","group"=>"staroffice"],
"sm"=>["name"=>"StepMania","detail"=>"IANA: StepMania","media"=>"application","type"=>"vnd.stepmania.stepchart","group"=>""],
"sit"=>["name"=>"Stuffit Archive","detail"=>"Wikipedia: Stuffit","media"=>"application","type"=>"x-stuffit","group"=>""],
"sitx"=>["name"=>"Stuffit Archive","detail"=>"Wikipedia: Stuffit","media"=>"application","type"=>"x-stuffitx","group"=>""],
"sdkm"=>["name"=>"SudokuMagic","detail"=>"IANA: SudokuMagic","media"=>"application","type"=>"vnd.solent.sdkm+xml","group"=>""],
"xo"=>["name"=>"Sugar Linux Application Bundle","detail"=>"IANA: Sugar Linux App Bundle","media"=>"application","type"=>"vnd.olpc-sugar","group"=>"linux"],
"au"=>["name"=>"Sun Audio - Au file format","detail"=>"Wikipedia: Sun audio","media"=>"audio","type"=>"basic","group"=>""],
"wqd"=>["name"=>"SundaHus WQ","detail"=>"IANA: SundaHus WQ","media"=>"application","type"=>"vnd.wqd","group"=>""],
"sis"=>["name"=>"Symbian Install Package","detail"=>"IANA: Symbian Install","media"=>"application","type"=>"vnd.symbian.install","group"=>""],
"smi"=>["name"=>"Synchronized Multimedia Integration Language","detail"=>"RFC 4536","media"=>"application","type"=>"smil+xml","group"=>"xml"],
"xsm"=>["name"=>"SyncML","detail"=>"IANA: SyncML","media"=>"application","type"=>"vnd.syncml+xml","group"=>"xml"],
"bdm"=>["name"=>"SyncML - Device Management","detail"=>"IANA: SyncML","media"=>"application","type"=>"vnd.syncml.dm+wbxml","group"=>"xml"],
"xdm"=>["name"=>"SyncML - Device Management","detail"=>"IANA: SyncML","media"=>"application","type"=>"vnd.syncml.dm+xml","group"=>"xml"],
"sv4cpio"=>["name"=>"System V Release 4 CPIO Archive","detail"=>"Wikipedia: pax","media"=>"application","type"=>"x-sv4cpio","group"=>""],
"sv4crc"=>["name"=>"System V Release 4 CPIO Checksum Data","detail"=>"Wikipedia: pax","media"=>"application","type"=>"x-sv4crc","group"=>""],
"sbml"=>["name"=>"Systems Biology Markup Language","detail"=>"RFC 3823","media"=>"application","type"=>"sbml+xml","group"=>"xml"],
"tsv"=>["name"=>"Tab Seperated Values","detail"=>"Wikipedia: TSV","media"=>"text","type"=>"tab-separated-values","group"=>""],
"tiff"=>["name"=>"Tagged Image File Format","detail"=>"Wikipedia: TIFF","media"=>"image","type"=>"tiff","group"=>""],
"tao"=>["name"=>"Tao Intent","detail"=>"IANA: Tao Intent","media"=>"application","type"=>"vnd.tao.intent-module-archive","group"=>""],
"tar"=>["name"=>"Tar File (Tape Archive)","detail"=>"Wikipedia: Tar","media"=>"application","type"=>"x-tar","group"=>"compress"],
"tcl"=>["name"=>"Tcl Script","detail"=>"Wikipedia: Tcl","media"=>"application","type"=>"x-tcl","group"=>"web"],
"tex"=>["name"=>"TeX","detail"=>"Wikipedia: TeX","media"=>"application","type"=>"x-tex","group"=>""],
"tfm"=>["name"=>"TeX Font Metric","detail"=>"Wikipedia: TeX Font Metric","media"=>"application","type"=>"x-tex-tfm","group"=>"font"],
"tei"=>["name"=>"Text Encoding and Interchange","detail"=>"RFC 6129","media"=>"application","type"=>"tei+xml","group"=>""],
"txt"=>["name"=>"Text File","detail"=>"Wikipedia: Text File","media"=>"text","type"=>"plain","group"=>""],
"dxp"=>["name"=>"TIBCO Spotfire","detail"=>"IANA: TIBCO Spotfire","media"=>"application","type"=>"vnd.spotfire.dxp","group"=>""],
"sfs"=>["name"=>"TIBCO Spotfire","detail"=>"IANA: TIBCO Spotfire","media"=>"application","type"=>"vnd.spotfire.sfs","group"=>""],
"tsd"=>["name"=>"Time Stamped Data Envelope","detail"=>"RFC 5955","media"=>"application","type"=>"timestamped-data","group"=>""],
"tpt"=>["name"=>"TRI Systems Config","detail"=>"IANA: TRI Systems","media"=>"application","type"=>"vnd.trid.tpt","group"=>""],
"mxs"=>["name"=>"Triscape Map Explorer","detail"=>"IANA: Triscape Map Explorer","media"=>"application","type"=>"vnd.triscape.mxs","group"=>""],
"t"=>["name"=>"troff","detail"=>"Wikipedia: troff","media"=>"text","type"=>"troff","group"=>""],
"tra"=>["name"=>"True BASIC","detail"=>"IANA: True BASIC","media"=>"application","type"=>"vnd.trueapp","group"=>""],
"ttf"=>["name"=>"TrueType Font","detail"=>"Wikipedia: TrueType","media"=>"application","type"=>"x-font-ttf","group"=>"font"],
"ttl"=>["name"=>"Turtle (Terse RDF Triple Language)","detail"=>"Wikipedia: Turtle","media"=>"text","type"=>"turtle","group"=>""],
"umj"=>["name"=>"UMAJIN","detail"=>"IANA: UMAJIN","media"=>"application","type"=>"vnd.umajin","group"=>""],
"uoml"=>["name"=>"Unique Object Markup Language","detail"=>"IANA: UOML","media"=>"application","type"=>"vnd.uoml+xml","group"=>""],
"unityweb"=>["name"=>"Unity 3d","detail"=>"IANA: Unity 3d","media"=>"application","type"=>"vnd.unity","group"=>""],
"ufd"=>["name"=>"Universal Forms Description Language","detail"=>"IANA: Universal Forms Description Language","media"=>"application","type"=>"vnd.ufdl","group"=>""],
"uri"=>["name"=>"URI Resolution Services","detail"=>"RFC 2483","media"=>"text","type"=>"uri-list","group"=>"web"],
"utz"=>["name"=>"User Interface Quartz - Theme (Symbian)","detail"=>"IANA: User Interface Quartz","media"=>"application","type"=>"vnd.uiq.theme","group"=>""],
"ustar"=>["name"=>"Ustar (Uniform Standard Tape Archive)","detail"=>"Wikipedia: Ustar","media"=>"application","type"=>"x-ustar","group"=>""],
"uu"=>["name"=>"UUEncode","detail"=>"Wikipedia: UUEncode","media"=>"text","type"=>"x-uuencode","group"=>""],
"vcs"=>["name"=>"vCalendar","detail"=>"Wikipedia: vCalendar","media"=>"text","type"=>"x-vcalendar","group"=>"web"],
"vcf"=>["name"=>"vCard","detail"=>"Wikipedia: vCard","media"=>"text","type"=>"x-vcard","group"=>""],
"vcd"=>["name"=>"Video CD","detail"=>"Wikipedia: Video CD","media"=>"application","type"=>"x-cdlink","group"=>""],
"vsf"=>["name"=>"Viewport+","detail"=>"IANA: Viewport+","media"=>"application","type"=>"vnd.vsf","group"=>""],
"wrl"=>["name"=>"Virtual Reality Modeling Language","detail"=>"Wikipedia: VRML","media"=>"model","type"=>"vrml","group"=>"graphic"],
"vcx"=>["name"=>"VirtualCatalog","detail"=>"IANA: VirtualCatalog","media"=>"application","type"=>"vnd.vcx","group"=>"graphic"],
"mts"=>["name"=>"Virtue MTS","detail"=>"IANA: MTS","media"=>"model","type"=>"vnd.mts","group"=>""],
"vtu"=>["name"=>"Virtue VTU","detail"=>"IANA: VTU","media"=>"model","type"=>"vnd.vtu","group"=>""],
"vis"=>["name"=>"Visionary","detail"=>"IANA: Visionary","media"=>"application","type"=>"vnd.visionary","group"=>""],
"viv"=>["name"=>"Vivo","detail"=>"IANA: Vivo","media"=>"video","type"=>"vnd.vivo","group"=>""],
"ccxml"=>["name"=>"Voice Browser Call Control","detail"=>"Voice Browser Call Control: CCXML Version 1.0","media"=>"application","type"=>"ccxml+xml","group"=>"xml"],
"vxml"=>["name"=>"VoiceXML","detail"=>"RFC 4267","media"=>"application","type"=>"voicexml+xml","group"=>"xml"],
"src"=>["name"=>"WAIS Source","detail"=>"YoLinux","media"=>"application","type"=>"x-wais-source","group"=>"linux"],
"wbxml"=>["name"=>"WAP Binary XML (WBXML)","detail"=>"IANA: WBXML","media"=>"application","type"=>"vnd.wap.wbxml","group"=>"xml"],
"wbmp"=>["name"=>"WAP Bitamp (WBMP)","detail"=>"IANA: WBMP","media"=>"image","type"=>"vnd.wap.wbmp","group"=>"raw"],
"wav"=>["name"=>"Waveform Audio File Format (WAV)","detail"=>"Wikipedia: WAV","media"=>"audio","type"=>"x-wav","group"=>"raw"],
"davmount"=>["name"=>"Web Distributed Authoring and Versioning","detail"=>"RFC 4918","media"=>"application","type"=>"davmount+xml","group"=>"xml"],
"woff"=>["name"=>"Web Open Font Format","detail"=>"Wikipedia: Web Open Font Format","media"=>"application","type"=>"x-font-woff","group"=>"font"],
"wspolicy"=>["name"=>"Web Services Policy","detail"=>"W3C Web Services Policy","media"=>"application","type"=>"wspolicy+xml","group"=>"xml"],
"webp"=>["name"=>"WebP Image","detail"=>"Wikipedia: WebP","media"=>"image","type"=>"webp","group"=>"web"],
"wtb"=>["name"=>"WebTurbo","detail"=>"IANA: WebTurbo","media"=>"application","type"=>"vnd.webturbo","group"=>"web"],
"wgt"=>["name"=>"Widget Packaging and XML Configuration","detail"=>"W3C Widget Packaging and XML Configuration","media"=>"application","type"=>"widget","group"=>"xml"],
"hlp"=>["name"=>"WinHelp","detail"=>"Wikipedia: WinHelp","media"=>"application","type"=>"winhlp","group"=>"web"],
"wml"=>["name"=>"Wireless Markup Language (WML)","detail"=>"Wikipedia: WML","media"=>"text","type"=>"vnd.wap.wml","group"=>""],
"wmls"=>["name"=>"Wireless Markup Language Script (WMLScript)","detail"=>"Wikipedia: WMLScript","media"=>"text","type"=>"vnd.wap.wmlscript","group"=>""],
"wmlsc"=>["name"=>"WMLScript","detail"=>"IANA: WMLScript","media"=>"application","type"=>"vnd.wap.wmlscriptc","group"=>"program"],
"wpd"=>["name"=>"Wordperfect","detail"=>"IANA: Wordperfect","media"=>"application","type"=>"vnd.wordperfect","group"=>""],
"stf"=>["name"=>"Worldtalk","detail"=>"IANA: Worldtalk","media"=>"application","type"=>"vnd.wt.stf","group"=>""],
"wsdl"=>["name"=>"WSDL - Web Services Description Language","detail"=>"W3C Web Service Description Language","media"=>"application","type"=>"wsdl+xml","group"=>"xml"],
"xbm"=>["name"=>"X BitMap","detail"=>"Wikipedia: X BitMap","media"=>"image","type"=>"x-xbitmap","group"=>"graphic"],
"xpm"=>["name"=>"X PixMap","detail"=>"Wikipedia: X PixMap","media"=>"image","type"=>"x-xpixmap","group"=>"graphic"],
"xwd"=>["name"=>"X Window Dump","detail"=>"Wikipedia: X Window Dump","media"=>"image","type"=>"x-xwindowdump","group"=>""],
"der"=>["name"=>"X.509 Certificate","detail"=>"Wikipedia: X.509","media"=>"application","type"=>"x-x509-ca-cert","group"=>"cryptographic"],
"fig"=>["name"=>"Xfig","detail"=>"Wikipedia: Xfig","media"=>"application","type"=>"x-xfig","group"=>""],
"xhtml"=>["name"=>"XHTML - The Extensible HyperText Markup Language","detail"=>"W3C XHTML","media"=>"application","type"=>"xhtml+xml","group"=>"web"],
"xml"=>["name"=>"XML - Extensible Markup Language","detail"=>"W3C XML","media"=>"application","type"=>"xml","group"=>"xml"],
"xdf"=>["name"=>"XML Configuration Access Protocol - XCAP Diff","detail"=>"Wikipedia: XCAP","media"=>"application","type"=>"xcap-diff+xml","group"=>""],
"xenc"=>["name"=>"XML Encryption Syntax and Processing","detail"=>"W3C XML Encryption Syntax and Processing","media"=>"application","type"=>"xenc+xml","group"=>"xml"],
"xer"=>["name"=>"XML Patch Framework","detail"=>"RFC 5261","media"=>"application","type"=>"patch-ops-error+xml","group"=>"xml"],
"rl"=>["name"=>"XML Resource Lists","detail"=>"RFC 4826","media"=>"application","type"=>"resource-lists+xml","group"=>"xml"],
"rs"=>["name"=>"XML Resource Lists","detail"=>"RFC 4826","media"=>"application","type"=>"rls-services+xml","group"=>"xml"],
"rld"=>["name"=>"XML Resource Lists Diff","detail"=>"RFC 4826","media"=>"application","type"=>"resource-lists-diff+xml","group"=>"xml"],
"xslt"=>["name"=>"XML Transformations","detail"=>"W3C XSLT","media"=>"application","type"=>"xslt+xml","group"=>"xml"],
"xop"=>["name"=>"XML-Binary Optimized Packaging","detail"=>"W3C XOP","media"=>"application","type"=>"xop+xml","group"=>"xml"],
"xpi"=>["name"=>"XPInstall - Mozilla","detail"=>"Wikipedia: XPI","media"=>"application","type"=>"x-xpinstall","group"=>"xml"],
"xspf"=>["name"=>"XSPF - XML Shareable Playlist Format","detail"=>"XML Shareable Playlist Format","media"=>"application","type"=>"xspf+xml","group"=>"xml"],
"xul"=>["name"=>"XUL - XML User Interface Language","detail"=>"IANA: XUL","media"=>"application","type"=>"vnd.mozilla.xul+xml","group"=>"xml"],
"xyz"=>["name"=>"XYZ File Format","detail"=>"Wikipedia: XYZ File Format","media"=>"chemical","type"=>"x-xyz","group"=>""],
"yaml"=>["name"=>"YAML Ain't Markup Language / Yet Another Markup Language","detail"=>"YAML: YAML Ain't Markup Language","media"=>"text","type"=>"yaml","group"=>"yaml"],
"yang"=>["name"=>"YANG Data Modeling Language","detail"=>"Wikipedia: YANG","media"=>"application","type"=>"yang","group"=>""],
"yin"=>["name"=>"YIN (YANG - XML)","detail"=>"Wikipedia: YANG","media"=>"application","type"=>"yin+xml","group"=>"xml"],
"zir"=>["name"=>"Z.U.L. Geometry","detail"=>"IANA: Z.U.L.","media"=>"application","type"=>"vnd.zul","group"=>"graphic"],
"zip"=>["name"=>"Zip Archive","detail"=>"Wikipedia: Zip","media"=>"application","type"=>"zip","group"=>"compress"],
"zmm"=>["name"=>"ZVUE Media Manager","detail"=>"IANA: ZVUE Media Manager","media"=>"application","type"=>"vnd.handheld-entertainment+xml","group"=>""],
"zaz"=>["name"=>"Zzazz Deck","detail"=>"IANA: Zzazz","media"=>"application","type"=>"vnd.zzazz.deck+xml","group"=>"xml"]
 ];



    

    public function __construct(

    ){

    }

    /**
     * @return mixed
     */
    public function getAllAlbumData($data)
    {
       $data = json_decode($dta);

       if(isset($data['path'])){
            $bitPath= explode('.',$data['path']);
             $countPoint = count($bitPath);
             $extension = $bitPath[$countPoint-1];

             if(array_key_exists($extension,$mediatypes)){
                  $mediatypes[$extension]['size'] = $this->formatBytes($data['size']);
                 $albumdata = $mediatypes[$extension];
             }else{
                 $albumdata = ["name"=>"unknow","detail"=>"unknow","media"=>"unknow","type"=>"unknow","group"=>""]
             }
       }


//{
//    etag: "2381313c3ccb41163008f867b1f7f06c",
//    mimetype: "image/jpeg",
//    mtime: 1545068194,
//    nodeid: 24263,
//    owner: {
//        uid: "5c0edebf37620c5573697b2d",
//        displayname: "Nombre Apellido"
//    },
//    displayname: "Nombre Apellido",
//    uid: "5c0edebf37620c5573697b2d",
//    path: "/5c0edebf37620c5573697b2d/files/Romantique.jpg",
//    permissions: 27,
//    sharedwithuser: false,
//    size: 160101
//}
    }

    public function formatBytes($bytes, $precision = 2) { 
        $units =  ['B', 'KB', 'MB', 'GB', 'TB']; 
    
        $bytes = max($bytes, 0); 
        $pow = floor(($bytes ? log($bytes) : 0) / log(1024)); 
        $pow = min($pow, count($units) - 1); 
    
        // Uncomment one of the following alternatives
        // $bytes /= pow(1024, $pow);
        // $bytes /= (1 << (10 * $pow)); 
    
        return round($bytes, $precision) . ' ' . $units[$pow]; 
    } 




}

